package com.erp.PtPurchaseDetails.Model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Subselect;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;


@AllArgsConstructor
@NoArgsConstructor
@Data
@Entity
@Immutable
@Subselect("select * from ptv_purchase_order_details")
public class CPtPurchaseOrderDetailsViewModel {

	@Id
	private int purchase_order_details_transaction_id;
	private Integer sr_no;
	private String company_name;
	private String company_branch_name;
	private String financial_year;
	private String purchase_order_no;
	private String purchase_order_date;
	private Integer purchase_order_version;
	private Integer product_rm_purchase_unit_id;
	private String purchase_order_type;
	private String product_type_name;
	private String product_type_short_name;
	private String product_type_group;
	private String indent_no;
	private String indent_date;
	private String indent_version;
	private String product_material_code;
	private String product_material_name;
	private String product_material_print_name;
	private String product_material_tech_spect;
	private int lead_time;
	private double product_material_std_weight;
	private String product_material_stock_unit_name;
	private String product_material_purchase_unit_name;
	private String product_packing_name;
	private String hsn_sac_type;
	private String hsn_sac_code;
	private String hsn_sac_description;
	private double hsn_sac_rate;
	private String product_make_name;
	private String product_category1_name;
	private String product_category2_name;
//	private String product_category3_name;
//	private String product_category4_name;
//	private String product_category5_name;
	private String product_material_type_name;
	private String product_material_grade_name;
	private String product_material_shape_name;
	private String product_material_oem_part_code;
	private String product_material_our_part_code;
	private double available_stock_quantity;
	private double available_stock_weight;
	private double product_material_po_quantity;
	private double product_material_conversion_factor;
	private double product_material_po_weight;
	private double product_material_po_approved_quantity;
	private double product_material_po_approved_weight;
	private double product_material_po_rejected_quantity;
	private double product_material_po_rejected_weight;
	private double pree_closed_quantity;
	private double pree_closed_weight;
	private double purchase_return_quantity;
	private double purchase_return_weight;
	private double material_rate;
	private double material_basic_amount;
	private double material_discount_percent;
	private double material_discount_amount;
	private double material_taxable_amount;
	private double material_cgst_percent;
	private double material_cgst_total;
	private double material_sgst_percent;
	private double material_sgst_total;
	private double material_igst_percent;
	private double material_igst_total;
	private double material_total_amount;
	private double material_freight_amount;
	private String material_schedule_date;
	private String purchase_order_item_status;
	private String purchase_order_mail_sent_status;
	private double pending_quantity;
	private double pending_weight;
	private double excess_quantity;
	private double excess_weight;
	private double production_issue_quantity;
	private double production_issue_weight;
	private double production_issue_return_quantity;
	private double production_issue_return_weight;
	private double production_issue_rejection_quantity;
	private double production_issue_rejection_weight;
	private double assembly_production_issue_quantity;
	private double assembly_production_issue_weight;
	private double sales_quantity;
	private double sales_weight;
	private double sales_return_quantity;
	private double sales_return_weight;
	private double sales_rejection_quantity;
	private double sales_rejection_weight;
	private double transfer_issue_quantity;
	private double transfer_issue_weight;
	private double transfer_receipt_quantity;
	private double transfer_receipt_weight;
	private double outsources_out_quantity;
	private double outsources_out_weight;
	private double outsources_in_quantity;
	private double outsources_in_weight;
	private double outsources_rejection_quantity;
	private double outsources_rejection_weight;
	private double loan_receipt_quantity;
	private double loan_receipt_weight;
	private double loan_issue_quantity;
	private double loan_issue_weight;
	private double cancel_quantity;
	private double cancel_weight;
	private double difference_quantity;
	private double difference_weight;
	private String material_po_approval_remark;
	private String department_name;
	private String sub_department_name;
	private String approved_by_name;
	private String approved_date;
	private String purchase_order_status_desc;
	private String purchase_order_item_status_desc;
	private String purchase_order_mail_sent_status_desc;
	private String supplier_name;
	private String supplier_state_name;
	private String indented_by_name;
	private String product_material_drawing_no;
	private String product_material_hsn_sac_code;
	private String purchase_order_status;
	private String city_name;
	private Integer supplier_id;
	private Integer supplier_state_id;
	private Integer supplier_city_id;
	private String supplier_contacts_ids;
	private String remark;

	private String company_cell_no;
	private String company_phone_no;
	private String company_EmailId;
	private String company_website;
	private String company_gst_no;
	private String company_pan_no;
	private String company_state;
	private String company_pincode;

	private Integer so_sr_no;
	private boolean is_active;
	private boolean is_delete;
	private String created_by;
	private Date created_on;
	private String modified_by;
	private Date modified_on;
	private Date deleted_on;
	private String deleted_by;
	private Integer company_id;
	private Integer company_branch_id;
	private Integer purchase_order_type_id;
	private Integer purchase_order_master_transaction_id;
	private Integer product_material_type_id;
	private Integer product_material_grade_id;
	private Integer product_material_shape_id;
	private Integer product_category1_id;
	private Integer product_category2_id;
	private Integer product_category3_id;
	private Integer product_category4_id;
	private Integer product_category5_id;
	private String product_material_id;
	private Integer product_material_unit_id;
	private Integer product_material_packing_id;
	private Integer product_material_hsn_code_id;
	private Integer department_id;
	private Integer indented_by_id;
	private Integer approved_by_id;
	private Integer expected_branch_id;
	private Integer expected_branch_state_id;
	private Integer expected_branch_city_id;
	private String customer_id;
	private String customer_order_no;
	private String customer_order_Date;
	private Integer prev_grn_quantity;
	private Integer prev_grn_weight;
	private Double prev_grn_bales_quantity;
	private Double prev_grn_bales_weight;
	private String customer_name;
	private String godown_name;
	private String godown_section_name;
	private String godown_section_beans_name;
	private Integer godown_id;
	private Integer godown_section_id;
	private Integer godown_section_beans_id;
	private Double product_material_po_quantity_qunital;
	private String cost_center_id;
	private Integer sub_department_id;
	private Double quantity_per_packing;
//	private Double available_rawmaterial_stock_quantity;
//	private Double available_rawmaterial_stock_weight;
	private String grn_item_status;
	private double prev_po_quantity;
	private double prev_po_weight;
	private String pre_closed_remark;
	private Integer currency_id;
	private String currency_name;

}
