package com.erp.MtDispatchChallanDetails.Model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Subselect;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Immutable
@Subselect("select * from mtv_dispatch_challan_details_trading")
public class CMtDispatchChallanDetailsTradingViewModel {

	@Id
	private int dispatch_challan_details_transaction_id;
	private String dispatch_challan_no;
	private String dispatch_challan_date;
	private Integer dispatch_challan_version;
	private String dispatch_challan_status_desc;
	private String consignee_name;
	private String consignee_state_name;
	private String approved_date;
	private String customer_gst_no;
	private String consignee_gst_no;
	private String customer_pan_no;
	private String consignee_pan_no;
	private String transporter_gst_no;
	private String vehicle_no;
	private String vehicle_type;
	private String transporter_challan_no;
	private String transporter_challan_date;
	private String loading_time;
	private String transport_mode;
	private String transaction_type;
	private String is_service;
	private String is_sez;
	private String interim;
	private String overall_schedule_date;
	private double basic_total;
	private double transport_amount;
	private double freight_amount;
	private boolean is_freight_taxable;
	private Integer freight_hsn_code_id;
	private double packing_amount;
	private double discount_percent;
	private double discount_amount;
	private double other_amount;
	private double taxable_total;
	private double cgst_percent;
	private double cgst_total;
	private double sgst_percent;
	private double sgst_total;
	private double igst_percent;
	private double igst_total;
	private double roundoff;
	private double grand_total;
	private Integer agent_id;
	private String agent_name;
	private double agent_percent;
	private double agent_amount;
	private String agent_paid_status;
	private String sales_order_no;
	private String sales_order_Date;
	private Integer sales_order_version;
	private boolean pree_close_flag = Boolean.FALSE;
	private Double pree_close_quantity;
	private String dispatch_challan_creation_type_desc;
	private String dispatch_challan_item_status_desc;
	private String customer_order_no;
	private String customer_order_Date;
	//	private String customer_order_version;
	private String dispatch_schedule_no;
	private String dispatch_schedule_date;
	private Integer dispatch_schedule_version;
	private Integer sr_no;
//	private Double product_material_std_weight;
	private String product_material_id;
	private String so_sr_no;
//	private String product_type_group;
	private String product_material_name;
	private String product_material_print_name;
	private String product_material_tech_spect;
	private Integer product_material_unit_id;
	private String product_unit_name;
	private Integer product_material_packing_id;
	private String product_packing_name;
	private double dispatch_quantity;
	private double dispatch_weight;
	private Integer hsn_sac_id;
	private String hsn_sac_code;
	private double hsn_sac_rate;
	private double hsn_sac_percent;
	private double item_rate;
	private double item_amount;
	private double item_discount_percent;
	private double item_discount_amount;
	private double item_taxable_amount;
	private double item_cgst_percent;
	private double item_cgst_amount;
	private double item_sgst_percent;
	private double item_sgst_amount;
	private double item_igst_percent;
	private double item_igst_amount;
	private double item_total_amount;
	private double item_freight_amount;
	private double dispatch_return_quantity;
	private double dispatch_return_weight;
	private double pending_quantity;
	private double pending_weight;
	private Date expected_schedule_date;
	private Integer delayed_days;
	private double invoice_quantity;
	private double invoice_weight;
	private String dispatch_challan_item_status;
	private String dispatch_challan_type;
	private String remark;
	private String company_name;
	private String company_branch_name;
	private String company_address1;
	private String company_address2;
	private String company_cell_no;
	private String company_phone_no;
	private String company_EmailId;
	private String company_website;
	private String company_gst_no;
	private String company_pan_no;
	private String company_state;
	private String company_pincode;
	private String company_udyog_adhar_no;
	private String financial_year;
	private String customer_email;
	private String customer_city_name;
	private String consignee_email;
	private String consignee_city_name;
	private boolean is_active;
	private boolean is_delete;
	private String created_by;
	private Date created_on;
	private String modified_by;
	private Date modified_on;
	private String deleted_by;
	private Date deleted_on;
	private Integer company_id;
	private Integer dispatch_challan_master_transaction_id;
	private Integer product_type_id;
	private Integer company_branch_id;
	private Integer expected_branch_id;
	private Integer dispatch_challan_type_id;
	private Integer customer_id;
	private String customer_contacts_ids;
	private Integer customer_state_id;
	private Integer customer_city_id;
	private Integer consignee_id;
	private Integer consignee_state_id;
	private Integer consignee_city_id;
	private Integer transporter_id;
	private Integer approved_by_id;
	private String set_no;
    private String product_material_code;
	private Double dispatch_schedule_quantity ;

}
