-- cmv_customer_rpt source

create or replace algorithm = UNDEFINED view `cmv_customer_rpt` as
select
    concat(`v`.`customer_name`, ':Customer name:Y:T') as `customer_name`,
    concat(`v`.`customer_type`, ':Customer Type:Y:P:CustomerTypes') as `customer_type`,
    concat(`v`.`customer_code`, ':Customer Code:Y:T:') as `customer_code`,
    concat(`v`.`customer_short_name`, ':Customer Short Name:O:N:') as `customer_short_name`,
    concat(`v`.`customer_sector`, ':Customer Sector:N:N:') as `customer_sector`,
    concat(`v`.`nature_of_business`, ':Nature Of Business:N:N:') as `nature_of_business`,
    concat(`v`.`customer_payment_terms`, ':Customer Payment Terms:Y:P:PaymentTermDays') as `customer_payment_terms`,
    concat(`v`.`customer_rating`, ':Customer Rating:N:N:') as `customer_rating`,
    concat(`v`.`customer_history`, ':Customer History:N:N:') as `customer_history`,
    concat(`v`.`branch_type`, ':Branch Type:Y:H:(Main,Sub)') as `branch_type`,
    concat(`v`.`cust_branch_short_name`, ':Branch Short Name:O:N:') as `cust_branch_short_name`,
    concat(`v`.`cust_branch_address1`, ':Branch Address1:O:N:') as `cust_branch_address1`,
    concat(`v`.`cust_branch_address2`, ':Branch Address2:O:N:') as `cust_branch_address2`,
    concat(`v`.`cust_branch_pincode`, ':Branch Pincode:O:N:') as `cust_branch_pincode`,
    concat(`v`.`country_name`, ':Country Name:Y:C:cmv_country:F') as `country_name`,
    concat(`v`.`state_name`, ':State Name:Y:C:cmv_state:F') as `state_name`,
    concat(`v`.`district_name`, ':District Name:N:N:cmv_district:F') as `district_name`,
    concat(`v`.`city_name`, ':City Name:Y:C:cmv_city:F') as `city_name`,
    concat(`v`.`cust_branch_region`, ':Branch Region:N:N:Regions') as `cust_branch_region`,
    concat(`v`.`cust_branch_phone_no`, ':Branch Phone No:O:N:') as `cust_branch_phone_no`,
    concat(`v`.`cust_branch_cell_no`, ':Branch Cell No:O:N:') as `cust_branch_cell_no`,
    concat(`v`.`cust_branch_EmailId`, ':Branch Email Id:O:N:') as `cust_branch_EmailId`,
    concat(`v`.`cust_branch_website`, ':Branch Website:O:N:') as `cust_branch_website`,
    concat(`v`.`cust_branch_linkedin_profile`, ':Branch Linkedin Profile:O:N:') as `cust_branch_linkedin_profile`,
    concat(`v`.`cust_branch_twitter_profile`, ':Branch Twitter Profile:O:N:') as `cust_branch_twitter_profile`,
    concat(`v`.`cust_branch_facebook_profile`, ':Branch Facebook Profile:O:N:') as `cust_branch_facebook_profile`,
    concat(`v`.`cust_branch_gst_no`, ':Branch Gst No:O:N:') as `cust_branch_gst_no`,
    concat(`v`.`cust_branch_gst_division`, ':Branch Gst Division:O:N:') as `cust_branch_gst_division`,
    concat(`v`.`cust_branch_gst_range`, ':Branch Gst Range:O:N:') as `cust_branch_gst_range`,
    concat(`v`.`cust_branch_pan_no`, ':Branch Pan No:O:N:') as `cust_branch_pan_no`,
    concat(`v`.`cust_branch_udyog_adhar_no`, ':Branch Udyog Adhar No:O:N:') as `cust_branch_udyog_adhar_no`,
    concat(`v`.`cust_branch_vat_no`, ':Branch Vat No:O:N:') as `cust_branch_vat_no`,
    concat(`v`.`cust_branch_service_tax_no`, ':Branch Service Tax No:O:N:') as `cust_branch_service_tax_no`,
    concat(`v`.`cust_branch_excise_no`, ':Branch Excise No:N:N:') as `cust_branch_excise_no`,
    concat(`v`.`cust_branch_cst_no`, ':Branch Cst No:O:N:') as `cust_branch_cst_no`,
    concat(`v`.`cust_branch_bst_no`, ':Branch Bst No:O:N:') as `cust_branch_bst_no`,
    concat(`v`.`cust_branch_tally_id`, ':Branch Tally Id:O:N:') as `cust_branch_tally_id`,
    concat(`v`.`cust_branch_rating`, ':Branch Rating:O:N:') as `cust_branch_rating`,
    concat(`v`.`cust_branch_gl_codes`, ':Branch Gl Codes:O:N:') as `cust_branch_gl_codes`,
    concat(`v`.`is_sez`, ':Is Sez:Y:H:(Yes,No)') as `is_sez`,
    concat(`v`.`sez_name`, ':Sez Name:O:N:') as `sez_name`,
    concat(`v`.`pysical_distance`, ':Pysical Distance:Y:T:') as `pysical_distance`,
    concat(`v`.`remark`, ':Remark:N:N:') as `remark`,
    concat(`v`.`company_name`, ':Company Name:Y:C:cmv_company_summary:F') as `company_name`,
    concat(`v`.`company_branch_name`, ':Company Branch Name:Y:C:cmv_company_branch_summary:F') as `company_branch_name`,
    concat(case when `v`.`is_active` = 1 then 'Active' else 'In Active' end, ':Active Status:Y:H:(Active, In Active)') as `Active`,
    concat(case when `v`.`is_delete` = 1 then 'Yes' else 'No' end, ':Deleted Status:Y:H:(Yes, No)') as `Deleted`,
    concat(`v`.`created_by`, ':Created By:O:N:') as `created_by`,
    concat(`v`.`created_on`, ':Created On:O:N:') as `created_on`,
    concat(`v`.`modified_by`, ':Modified By:O:N:') as `modified_by`,
    concat(`v`.`modified_on`, ':Modified On:O:N:') as `modified_on`,
    concat(`v`.`deleted_by`, ':Deleted By:O:N:') as `deleted_by`,
    concat(`v`.`deleted_on`, ':Deleted On:O:N:') as `deleted_on`,
    concat(`v`.`company_id`, ':Company Id:N:N:') as `company_id`,
    concat(`v`.`company_branch_id`, ':Company Branch Id:O:N:') as `company_branch_id`,
    concat(`v`.`customer_id`, ':Customer Id:O:N:') as `customer_id`,
    concat(`v`.`cust_branch_accounts_id`, ':Branch Accounts Id:N:N:') as `cust_branch_accounts_id`,
    concat(`v`.`customer_accounts_id`, ':Customer Accounts Id:N:N:') as `customer_accounts_id`,
    concat(`v`.`customer_gl_codes`, ':Customer GL Codes:N:N:') as `customer_gl_codes`,
    concat(`v`.`cust_branch_city_id`, ':Branch City Id:N:N:') as `cust_branch_city_id`,
    concat(`v`.`cust_branch_district_id`, ':Branch District Id:N:N:') as `cust_branch_district_id`,
    concat(`v`.`cust_branch_state_id`, ':Branch State Id:N:N:') as `cust_branch_state_id`,
    concat(`v`.`cust_branch_country_id`, ':Branch Country Id:N:N:') as `cust_branch_country_id`
from
    `cmv_customer` `v`
limit 1;




-- cmv_customer_branch_rpt source

create or replace algorithm = UNDEFINED view `cmv_customer_branch_rpt` as
select
    concat(`v`.`customer_name`, ':Customer Name:Y:T') as `customer_name`,
    concat(`v`.`cust_branch_name`, ':Branch Name:Y:T') as `cust_branch_name`,
    concat(`v`.`customer_type`, ':Customer Type:Y:P:CustomerTypes') as `customer_type`,
    concat(`v`.`customer_code`, ':Customer Code:Y:T:') as `customer_code`,
    concat(`v`.`customer_short_name`, ':Customer Short Name:O:N:') as `customer_short_name`,
    concat(`v`.`customer_sector`, ':Customer Sector:N:N:') as `customer_sector`,
    concat(`v`.`nature_of_business`, ':Nature Of Business:N:N:') as `nature_of_business`,
    concat(`v`.`customer_payment_terms`, ':Property Name:Y:P:PaymentTermDays') as `customer_payment_terms`,
    concat(`v`.`customer_rating`, ':Customer Rating:N:N:') as `customer_rating`,
    concat(`v`.`customer_history`, ':Customer History:N:N:') as `customer_history`,
    concat(`v`.`branch_type`, ':Branch Type:O:N:') as `branch_type`,
    concat(`v`.`cust_branch_vendor_code`, ':Branch Vendor Code:O:N:') as `cust_branch_vendor_code`,
    concat(`v`.`cust_branch_short_name`, ':Branch Short Name:O:N:') as `cust_branch_short_name`,
    concat(`v`.`cust_branch_address1`, ':Branch Address1:O:N:') as `cust_branch_address1`,
    concat(`v`.`cust_branch_address2`, ':Branch Address2:O:N:') as `cust_branch_address2`,
    concat(`v`.`cust_branch_pincode`, ':Branch Pincode:O:N:') as `cust_branch_pincode`,
    concat(`v`.`district_name`, ':District Name:N:N:cmv_district:F') as `district_name`,
    concat(`v`.`state_name`, ':State Name:Y:C:cmv_state:F') as `state_name`,
    concat(`v`.`country_name`, ':Country Name:Y:C:cmv_country:F') as `country_name`,
    concat(`v`.`city_name`, ':City Name:Y:C:cmv_city:F') as `city_name`,
    concat(`v`.`cust_branch_region`, ':Branch Region:N:N:Regions') as `cust_branch_region`,
    concat(`v`.`cust_branch_phone_no`, ':Branch Phone No:O:N:') as `cust_branch_phone_no`,
    concat(`v`.`cust_branch_cell_no`, ':Branch Cell No:O:N:') as `cust_branch_cell_no`,
    concat(`v`.`cust_branch_EmailId`, ':Branch EmailId:O:N:') as `cust_branch_EmailId`,
    concat(`v`.`cust_branch_website`, ':Branch Website:O:N:') as `cust_branch_website`,
    concat(`v`.`cust_branch_linkedin_profile`, ':Branch Linkedin Profile:O:N:') as `cust_branch_linkedin_profile`,
    concat(`v`.`cust_branch_twitter_profile`, ':Branch Twitter Profile:O:N:') as `cust_branch_twitter_profile`,
    concat(`v`.`cust_branch_facebook_profile`, ':Branch Facebook Profile:O:N:') as `cust_branch_facebook_profile`,
    concat(`v`.`cust_branch_gst_no`, ':Branch Gst No:O:N:') as `cust_branch_gst_no`,
    concat(`v`.`cust_branch_gst_division`, ':Branch Gst Division:O:N:') as `cust_branch_gst_division`,
    concat(`v`.`cust_branch_gst_range`, ':Branch Gst Range:O:N:') as `cust_branch_gst_range`,
    concat(`v`.`cust_branch_pan_no`, ':Branch Pan No:O:N:') as `cust_branch_pan_no`,
    concat(`v`.`cust_branch_udyog_adhar_no`, ':Branch Udyog Adhar No:O:N:') as `cust_branch_udyog_adhar_no`,
    concat(`v`.`cust_branch_vat_no`, ':Branch Vat No:O:N:') as `cust_branch_vat_no`,
    concat(`v`.`cust_branch_service_tax_no`, ':Branch Service Tax No:O:N:') as `cust_branch_service_tax_no`,
    concat(`v`.`cust_branch_excise_no`, ':Branch Excise No:N:N:') as `cust_branch_excise_no`,
    concat(`v`.`cust_branch_cst_no`, ':Branch Cst No:O:N:') as `cust_branch_cst_no`,
    concat(`v`.`cust_branch_bst_no`, ':Branch Bst No:O:N:') as `cust_branch_bst_no`,
    concat(`v`.`cust_branch_tally_id`, 'Branch Tally Id:O:N:') as `cust_branch_tally_id`,
    concat(`v`.`cust_branch_rating`, ':Branch Rating:Y:T:') as `cust_branch_rating`,
    concat(`v`.`cust_branch_gl_codes`, ':Branch Gl Codes:O:N:') as `cust_branch_gl_codes`,
    concat(`v`.`cust_branch_accounts_id`, ':Branch Accounts Id:O:N:') as `cust_branch_accounts_id`,
    concat(`v`.`cust_branch_payment_terms`, ':Property Name:Y:P:PaymentTermDays') as `cust_branch_payment_terms`,
    concat(`v`.`cust_branch_blocked`, ':Branch Blocked:Y:H:(Yes,No)') as `cust_branch_blocked`,
    concat(`v`.`cust_branch_blocked_remark`, ':Branch Blocked Remark:O:N:') as `cust_branch_blocked_remark`,
    concat(`v`.`cust_branch_payment_blocked`, 'Branch Payment Blocked:Y:H:(Yes,No)') as `cust_branch_payment_blocked`,
    concat(`v`.`cust_payment_blocked_remark`, ':Branch Payment Blocked Remark:O:N:') as `cust_payment_blocked_remark`,
    concat(`v`.`is_sez`, ':Is Sez:Y:H:(Yes,No)') as `is_sez`,
    concat(`v`.`sez_name`, ':Sez Name:O:N:') as `sez_name`,
    concat(`v`.`pysical_distance`, ':Pysical Distance:Y:T:') as `pysical_distance`,
    concat(`v`.`company_name`, ':Company Name:Y:C:cmv_company_summary:F') as `company_name`,
    concat(`v`.`company_branch_name`, ':Company Branch:Y:C:cmv_company_branch:F') as `company_branch_name`,
    concat(case when `v`.`is_active` = 1 then 'Active' else 'In Active' end, ':Active Status:Y:H:(Active, In Active)') as `Active`,
    concat(case when `v`.`is_delete` = 1 then 'Yes' else 'No' end, ':Deleted Status:Y:H:(Yes, No)') as `Deleted`,
    concat(`v`.`created_by`, ':Created By:O:N:') as `created_by`,
    concat(`v`.`created_on`, ':Created On:O:N:') as `created_on`,
    concat(`v`.`modified_by`, ':Modified By:O:N:') as `modified_by`,
    concat(`v`.`modified_on`, ':Modified On:O:N:') as `modified_on`,
    concat(`v`.`deleted_by`, ':Deleted By:O:N:') as `deleted_by`,
    concat(`v`.`deleted_on`, ':Deleted On:O:N:') as `deleted_on`,
    concat(`v`.`company_id`, ':Company Id:N:N:') as `company_id`,
    concat(`v`.`company_branch_id`, ':Company Branch Id:N:N:') as `company_branch_id`,
    concat(`v`.`cust_branch_id`, ':Company Branch Id:O:N:') as `cust_branch_id`,
    concat(`v`.`customer_gl_codes`, ':Customer Gl Codes:N:N:') as `customer_gl_codes`,
    concat(`v`.`customer_accounts_id`, ':Customer Accounts Id:N:N:') as `customer_accounts_id`,
    concat(`v`.`cust_branch_city_id`, ':Branch City Id:N:N:') as `cust_branch_city_id`,
    concat(`v`.`cust_branch_district_id`, 'Branch District Id:N:N:') as `cust_branch_district_id`,
    concat(`v`.`cust_branch_state_id`, ':Branch State Id:N:N:') as `cust_branch_state_id`,
    concat(`v`.`cust_branch_country_id`, ':Branch Country Id:N:N:') as `cust_branch_country_id`
from
    .`cmv_customer_branch` `v`
limit 1;