-- pt_grn_cotton_bales_order_tax_summary definition

CREATE TABLE `pt_grn_cotton_bales_order_tax_summary` (
  `grn_cotton_bales_tax_summary_transaction_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `company_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session  ',
  `company_branch_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*combo box with cmv_company_branch  and set default backend from session  *',
  `financial_year` varchar(20) NOT NULL,
  `purchase_order_master_transaction_id` bigint(20) DEFAULT NULL COMMENT '* read only back end auto generated id of Master*',
  `supplier_id` bigint(20) DEFAULT NULL COMMENT ' Data will come from Header  Data Grid Entry  ',
  `supplier_state_id` bigint(20) DEFAULT NULL COMMENT ' Data will come from Header  Data Grid Entry  ',
  `supplier_city_id` bigint(20) DEFAULT NULL COMMENT ' Data will come from Header  Data Grid Entry  ',
  `supplier_contacts_ids` varchar(1000) DEFAULT NULL COMMENT ' Data will come from Header  Data Grid Entry  ',
  `expected_branch_id` bigint(20) NOT NULL DEFAULT 1 COMMENT ' Data will come from Header  Data Grid Entry  ',
  `expected_branch_state_id` bigint(20) DEFAULT NULL COMMENT ' Data will come from Header  Data Grid Entry  ',
  `expected_branch_city_id` bigint(20) DEFAULT NULL COMMENT ' Data will come from Header  Data Grid Entry  ',
  `purchase_order_no` varchar(50) DEFAULT NULL COMMENT '*read only text box Combination of Company Short name/FyearShort name/ProductType_group / SO0000Last ID ',
  `purchase_order_date` date DEFAULT NULL COMMENT '* DTPpicker Data Entry',
  `purchase_order_version` bigint(20) DEFAULT 1 COMMENT '* read only text box auto generated next Version *',
  `hsn_code_id` bigint(20) DEFAULT NULL COMMENT '* Data Grid  with Export/Import excel format Entry shows HSN Wise /Tax percent wise cummulative Totals from Details Data Grid Entry  ',
  `summary_taxable_amount` decimal(18,4) DEFAULT 1.0000 COMMENT '* Data Grid  with Export/Import excel format Entry shows HSN Wise /Tax percent wise cummulative Totals from Details Data Grid Entry    ',
  `summary_cgst_percent` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry shows HSN Wise /Tax percent wise cummulative Totals from Details Data Grid Entry  ',
  `summary_cgst_total` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry shows HSN Wise /Tax percent wise cummulative Totals from Details Data Grid Entry  ',
  `summary_sgst_percent` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry shows HSN Wise /Tax percent wise cummulative Totals from Details Data Grid Entry  ',
  `summary_sgst_total` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry shows HSN Wise /Tax percent wise cummulative Totals from Details Data Grid Entry  ',
  `summary_igst_percent` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry shows HSN Wise /Tax percent wise cummulative Totals from Details Data Grid Entry  ',
  `summary_igst_total` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry shows HSN Wise /Tax percent wise cummulative Totals from Details Data Grid Entry  ',
  `summary_total_amount` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry shows HSN Wise /Tax percent wise cummulative Totals from Details Data Grid Entry  ',
  `tax_upload__status` varchar(1) DEFAULT 'P' COMMENT 'P-Pending,  C-Completed, X-Canceled  Data Grid   Will update when uploadted to Government sit ',
  `tax_upload_id` varchar(1000) DEFAULT NULL COMMENT '*Data Grid   Will update when uploadted to Government site',
  `tax_upload_date` date DEFAULT NULL COMMENT '* Data Grid   Will update when uploadted to Government sit',
  `remark` varchar(1000) DEFAULT NULL,
  `is_active` bit(1) DEFAULT b'1',
  `is_delete` bit(1) DEFAULT b'0',
  `created_by` varchar(255) DEFAULT '1',
  `created_on` datetime DEFAULT NULL,
  `modified_by` varchar(255) DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  `deleted_on` datetime DEFAULT NULL,
  `goods_receipt_no` varchar(50) NOT NULL COMMENT ' * will used from  Header part data',
  `goods_receipt_date` date NOT NULL COMMENT '* will used from  Header part data ',
  `goods_receipt_version` bigint(20) NOT NULL DEFAULT 1 COMMENT '* will used from  Header part data',
  `grn_cotton_bales_master_transaction_id` bigint(20) NOT NULL,
  PRIMARY KEY (`grn_cotton_bales_tax_summary_transaction_id`)
);


-- pt_grn_cotton_bales_payment_terms definition

CREATE TABLE `pt_grn_cotton_bales_payment_terms` (
  `grn_cotton_bales_payment_terms_transaction_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `company_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session  ',
  `company_branch_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*combo box with cmv_company_branch  and set default backend from session  *',
  `financial_year` varchar(20) DEFAULT NULL COMMENT 'financial year ',
  `grn_cotton_bales_master_transaction_id` bigint(20) NOT NULL COMMENT '* read only back end auto generated from master id *',
  `goods_receipt_no` varchar(50) NOT NULL COMMENT '*read only text box Combination of Company Short name/FyearShort name/ProductType_group / SO0000Last ID ',
  `goods_receipt_date` date NOT NULL COMMENT '* DTPpicker Data Entry',
  `goods_receipt_version` bigint(20) NOT NULL DEFAULT 1 COMMENT '* read only text box auto generated next Version *',
  `purchase_order_no` varchar(50) NOT NULL COMMENT '*read only text box Combination of Company Short name/FyearShort name/ProductType_group / SO0000Last ID ',
  `purchase_order_date` date NOT NULL COMMENT '* DTPpicker Data Entry',
  `purchase_order_version` bigint(20) NOT NULL DEFAULT 1 COMMENT '* read only text box auto generated next Version *',
  `payment_terms_id` bigint(20) NOT NULL COMMENT '*  Data Grid  with  Dispaly from cm_payment_terms *',
  `payment_terms_name` varchar(255) NOT NULL COMMENT '*  Data Grid  with  Dispaly from cm_payment_terms *',
  `payment_terms_days` varchar(255) NOT NULL COMMENT '*  Data Grid  with  Dispaly from cm_payment_terms *',
  `payment_terms_grace_days` bigint(20) DEFAULT 0 COMMENT '*  Data Grid  with  Dispaly from cm_payment_terms *',
  `payment_terms_Milestome` varchar(255) DEFAULT NULL COMMENT '*  Data Grid  with text box Data Entry with validation*',
  `payment_percent` varchar(255) DEFAULT NULL COMMENT '*  Data Grid  with text box Data Entry with validation*',
  `payment_expected_value` decimal(18,4) DEFAULT 1.0000 COMMENT '*  Data Grid  with text box Data Entry with validation*',
  `payment_expected_date` date DEFAULT NULL COMMENT '*  Data Grid  with DTPpicker Data Entry with validation*',
  `payment_paid_flag` varchar(50) DEFAULT 'P' COMMENT ' * combo box  P-Pending, T-Partail,  R-Receipt',
  `payment_paid_transaction_id` varchar(1000) DEFAULT NULL COMMENT '* read only back end will get on : separation basis update once Payment Receipt Id*',
  `payment_paid_date` varchar(1000) DEFAULT NULL COMMENT '*   read only back end on : separation basis will get update once Payment Receipt Date *',
  `remark` varchar(255) DEFAULT NULL,
  `is_active` bit(1) DEFAULT b'1',
  `is_delete` bit(1) DEFAULT b'0',
  `created_by` varchar(255) DEFAULT '1',
  `created_on` datetime DEFAULT NULL,
  `modified_by` varchar(255) DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  `deleted_on` datetime DEFAULT NULL,
  PRIMARY KEY (`grn_cotton_bales_payment_terms_transaction_id`)
);