-- sm_product_material_stock_new definition

CREATE TABLE `sm_product_material_stock_new` (
  `stock_transaction_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '* Back End Entry auto generated from sm_product_material_stock_details *',
  `company_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session  ',
  `company_branch_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session ',
  `financial_year` varchar(20) NOT NULL DEFAULT '2024' COMMENT '*backend from session ',
  `product_type_group` varchar(100) DEFAULT 'NA' COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction level  *',
  `product_type_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction level  *',
  `product_material_id` varchar(20) NOT NULL DEFAULT '0' COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction level  *',
  `product_material_unit_id` bigint(20) DEFAULT 6 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `product_material_packing_id` bigint(20) DEFAULT 1 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `batch_no` text DEFAULT '0' COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction level *',
  `goods_receipt_no` varchar(255) DEFAULT NULL,
  `batch_rate` decimal(18,4) DEFAULT 1.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `opening_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `opening_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `opening_no_of_boxes` bigint(20) DEFAULT 0 COMMENT 'no of boxes for yarn stock',
  `reserve_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `reserve_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `reserve_no_of_boxes` bigint(20) DEFAULT 0 COMMENT 'no of boxes for yarn stock',
  `excess_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `excess_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `pree_closed_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `pree_closed_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `purchase_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `purchase_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `purchase_no_of_boxes` bigint(20) DEFAULT 0,
  `purchase_return_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `purchase_return_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `purchase_return_no_of_boxes` bigint(20) DEFAULT 0,
  `supplier_return_quantity` decimal(18,4) DEFAULT 0.0000,
  `supplier_return_weight` decimal(18,4) DEFAULT 0.0000,
  `supplier_return_boxes` bigint(20) DEFAULT 0,
  `production_issue_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `production_issue_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `issue_no_of_boxes` bigint(20) DEFAULT 0,
  `production_issue_return_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `production_issue_return_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `production_issue_return_boxes` bigint(20) DEFAULT 0,
  `production_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `production_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `production_no_of_boxes` bigint(20) DEFAULT 0,
  `sales_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `sales_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `sales_no_of_boxes` bigint(20) DEFAULT 0 COMMENT 'for store no. of rolls',
  `sales_return_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `sales_return_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `transfer_issue_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `transfer_issue_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `transfer_receipt_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `transfer_receipt_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `closing_balance_quantity` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `closing_balance_weight` decimal(18,4) DEFAULT 0.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `closing_no_of_boxes` bigint(20) DEFAULT 0 COMMENT 'no of boxes quantity of materials',
  `godown_id` bigint(20) NOT NULL DEFAULT 2 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `is_active` bit(1) DEFAULT b'1',
  `is_delete` bit(1) DEFAULT b'0',
  `created_by` varchar(255) DEFAULT '1',
  `created_on` datetime DEFAULT NULL,
  `modified_by` varchar(255) DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  `deleted_on` datetime DEFAULT NULL,
  PRIMARY KEY (`stock_transaction_id`),
  KEY `ind_product_material_id` (`product_material_id`,`is_delete`),
  KEY `ind_is_deleted` (`is_delete`),
  KEY `idx_product_rm_id` (`product_material_id`),
  KEY `idx_goods_receipt_no` (`goods_receipt_no`),
  KEY `idx_batch_no` (`batch_no`(1024))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;




-- sm_material_stock_log definition

CREATE TABLE `sm_material_stock_log` (
  `stock_log_transaction_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '* Back End Entry auto generated from sm_product_material_stock_details *',
  `company_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session  ',
  `company_branch_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session ',
  `financial_year` varchar(20) NOT NULL DEFAULT '2024' COMMENT '*backend from session ',
  `transaction_date` date DEFAULT NULL COMMENT '* NO Front End Only Back End Entry Data will come from respective transaction will updated on transaction to transaction level *',
  `transaction_type` varchar(30) DEFAULT NULL COMMENT '* type of transaction is created *',
  `transaction_no` varchar(30) DEFAULT NULL COMMENT '* type of transaction no *',
  `product_type_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction level  *',
  `product_category1_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction level  *',
  `product_category2_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction level  *',
  `product_material_id` varchar(20) NOT NULL DEFAULT '0' COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction level  *',
  `product_material_unit_id` bigint(20) DEFAULT 6 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `batch_no` text DEFAULT '0' COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction level *',
  `batch_rate` decimal(18,4) DEFAULT 1.0000 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `quantity` decimal(18,4) DEFAULT 0.0000,
  `weight` decimal(18,4) DEFAULT 0.0000,
  `no_of_boxes` bigint(20) DEFAULT 0,
  `godown_id` bigint(20) NOT NULL DEFAULT 2 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `godown_section_id` bigint(20) DEFAULT 2 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `godown_section_beans_id` bigint(20) DEFAULT 2 COMMENT '* NO Front End Only  Back End Entry Data will come from respective transaction will updated on transaction to transaction  level  *',
  `remark` varchar(1000) DEFAULT NULL,
  `is_delete` bit(1) DEFAULT b'0',
  `created_by` varchar(255) DEFAULT '1',
  `created_on` datetime DEFAULT NULL,
  `modified_by` varchar(255) DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  `deleted_on` datetime DEFAULT NULL,
  PRIMARY KEY (`stock_log_transaction_id`),
  KEY `ind_product_material_id` (`product_material_id`,`is_delete`),
  KEY `ind_is_deleted` (`is_delete`),
  KEY `idx_product_material_id` (`product_material_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;