INSERT INTO am_modules_forms (company_id,company_branch_id,module_id,sub_module_id,modules_menu_id,modules_sub_menu_id,modules_forms_name,display_sequence,display_name,menu_type,listing_component_name,listing_component_import_path,listing_navigation_url,form_component_name,form_component_import_path,form_navigation_url,icon_class,page_header,is_selected,is_active,is_delete,created_by,created_on,modified_by,modified_on,deleted_by,deleted_on,is_protected,header,footer,url_parameter) VALUES
	 (1,1,1,27,5,72,'Bales Mixing Chart',2,'Bales Mixing Chart','Production','<FrmBalesMixingChartListing />','import FrmBalesMixingChartListing from "Transactions/TCottonBalesManagement/TBalesMixingChart/FrmBalesMixingChartListing";','/Transactions/TCottonBalesManagement/TBalesMixingChart/FrmBalesMixingChartListing','<FrmBalesMixingChartEntry />','import FrmBalesMixingChartEntry from "Transactions/TCottonBalesManagement/TBalesMixingChart/FrmBalesMixingChartEntry";','/Transactions/TCottonBalesManagement/TBalesMixingChart/FrmBalesMixingChartEntry',NULL,'Bales Mixing Chart',0,1,0,NULL,NULL,NULL,NULL,NULL,NULL,0,1,1,'');


CREATE TABLE `pt_mixing_chart_cotton_bales` (
  `mixing_chart_cotton_bales_transaction_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `company_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session  ',
  `company_branch_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session ',
  `financial_year` varchar(20) NOT NULL,
  `mixing_chart_no` varchar(155) NOT NULL,
  `unit_testing_no` varchar(155) NOT NULL,
  `mixing_chart_date` date NOT NULL,
  `plant_id` bigint(20) NOT NULL,
  `mixing_by_id` bigint(20) NOT NULL,
  `pr_no` varchar(100) DEFAULT NULL,
  `batch_no` varchar(500) DEFAULT '0',
  `uhml` decimal(18,4) DEFAULT 0.0000,
  `ul` decimal(18,4) DEFAULT 0.0000,
  `mi` decimal(18,4) DEFAULT 0.0000,
  `mic` decimal(18,4) DEFAULT 0.0000,
  `str` decimal(18,4) DEFAULT 0.0000,
  `rd` decimal(18,4) DEFAULT 0.0000,
  `b_plus` decimal(18,4) DEFAULT 0.0000,
  `total_neps` decimal(18,4) DEFAULT 0.0000,
  `sc_n` decimal(18,4) DEFAULT 0.0000,
  `sfc_n` decimal(18,4) DEFAULT 0.0000,
  `trash` decimal(18,4) DEFAULT 0.0000,
  `moisture` decimal(18,4) DEFAULT 0.0000,
  `cg` decimal(18,4) DEFAULT 0.0000,
  `quality_testing_status` varchar(1) NOT NULL COMMENT 'C-Consumable, R-Rejected, I-Partial Rejected',
  `closing_balance_quantity` decimal(18,4) DEFAULT 0.0000,
  `closing_balance_weight` decimal(18,4) DEFAULT 0.0000,
  `issue_quantity` decimal(18,4) DEFAULT 0.0000,
  `issue_weight` decimal(18,4) DEFAULT 0.0000,
  `stock_quantity` decimal(18,4) DEFAULT 0.0000,
  `stock_weight` decimal(18,4) DEFAULT 0.0000,
  `is_active` bit(1) DEFAULT b'1',
  `is_delete` bit(1) DEFAULT b'0',
  `created_by` varchar(255) DEFAULT '1',
  `created_on` datetime DEFAULT NULL,
  `modified_by` varchar(255) DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  `deleted_on` datetime DEFAULT NULL,
  PRIMARY KEY (`mixing_chart_cotton_bales_transaction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;