
create or replace
algorithm = UNDEFINED view `mtv_sales_order_master_trading_summary_rpt` as
select
    concat(ifnull(`v`.`sales_order_no`, ''), ':Sales Order No:Y:T') as `sales_order_no`,
    concat(ifnull(`v`.`sales_order_date`, ''), ':Sales Order Date:Y:D:') as `sales_order_date`,
    concat(ifnull(`v`.`sales_order_status`, ''), ':Sales Order Status:Y:H:(Approved,Completed,Canceled,Rejected,Partial Issue,PreeClosed,Pending)') as `sales_order_status_desc`,
    concat(ifnull(`v`.`customer_name`, ''), ':Customer Name:Y:T') as `customer_name`,
    concat(ifnull(`v`.`customer_order_no`, ''), ':Customer Order No:Y:T') as `customer_order_no`,
    concat(ifnull(`v`.`customer_order_Date`, ''), ':Customer Order Date:Y:D:') as `customer_order_Date`,
    concat(ifnull(`v`.`job_type`, ''), ':Supplier Name:Y:T') as `job_type`,
    concat(ifnull(`v`.`supp_branch_name`, ''), ':Supplier Name:Y:T') as `supp_branch_name`,
    concat(ifnull(`v`.`lot_no`, ''), ':Lot No:Y:T:') as `lot_no`,
    concat(ifnull(`v`.`customer_name`, ''), ':Consignee Name:Y:T') as `consignee_name`,
    concat(ifnull(`v`.`department_name`, ''), ':Department Name:Y:C:cmv_department:F') as `department_name`,
    concat(ifnull(`v`.`sub_department_name`, ''), ':Sub Department Name:Y:C:cmv_department:F') as `sub_department_name`,
    concat(ifnull(`v`.`approved_by_name`, ''), ':Approved By:Y:T') as `approved_by_name`,
    concat(ifnull(`v`.`approved_date`, ''), ':Approved Date:Y:D:') as `approved_date`,
    concat(ifnull(`v`.`overall_schedule_date`, ''), ':Overall Schedule Date:Y:D:') as `overall_schedule_date`,
    concat(ifnull(`v`.`basic_total`, ''), ':Basic Total:O:N:') as `basic_total`,
    concat(ifnull(`v`.`transport_amount`, ''), ':Transport Amount:O:N:') as `transport_amount`,
    concat(ifnull(`v`.`hsn_sac_code`, ''), ':Freight Hsn Sac Code:O:N:') as `hsn_sac_code`,
    concat(ifnull(`v`.`hsn_sac_rate`, ''), ':Freight Hsn Sac Rate:O:N:') as `hsn_sac_rate`,
    concat(ifnull(`v`.`freight_amount`, ''), ':Freight Amount:O:N:') as `freight_amount`,
    concat(ifnull(`v`.`packing_amount`, ''), ':Packing Amount:O:N:') as `packing_amount`,
    concat(ifnull(`v`.`discount_percent`, ''), ':Discount Percent:O:N:') as `discount_percent`,
    concat(ifnull(`v`.`discount_amount`, ''), ':Discount Amount:O:N:') as `discount_amount`,
    concat(ifnull(`v`.`other_amount`, ''), ':Other Amount:O:N:') as `other_amount`,
    concat(ifnull(`v`.`taxable_total`, ''), ':Taxable Total:O:N:') as `taxable_total`,
    concat(ifnull(`v`.`cgst_total`, ''), ':CGST Total:O:N:') as `cgst_total`,
    concat(ifnull(`v`.`sgst_total`, ''), ':SGST Total:O:N:') as `sgst_total`,
    concat(ifnull(`v`.`igst_total`, ''), ':IGST Total:O:N:') as `igst_total`,
    concat(ifnull(`v`.`grand_total`, ''), ':Grand Total:O:N:') as `grand_total`,
    concat(ifnull(`v`.`roundoff`, ''), ':RoundOff:O:N:') as `roundoff`,
    concat(ifnull(`v`.`agent_name`, ''), ':Agent Name:O:N:') as `agent_name`,
    concat(ifnull(`v`.`agent_percent`, ''), ':Agent Percent:O:N:') as `agent_percent`,
    concat(ifnull(`v`.`agent_paid_status`, ''), ':Agent Paid Status:Y:H:Approved,Completed,Canceled,Pending') as `agent_paid_status_desc`,
    concat(ifnull(`v`.`sales_order_acceptance_status`, ''), ':Sales Order Acceptance Status:Y:H:Approved,Completed,Canceled,Pending') as `sales_order_acceptance_status_desc`,
    concat(ifnull(`v`.`sales_order_mail_sent_status`, ''), ':Sales Order Mail Sent Status:O:N:Approved,Completed,Canceled,Pending') as `sales_order_mail_sent_status_desc`,
    concat(ifnull(`v`.`status_remark`, ''), ':Status Remark:O:N:') as `status_remark`,
    concat(ifnull(`v`.`sales_order_version`, ''), ':Sales Order Version:O:N:') as `sales_order_version`,
    concat(ifnull(`v`.`other_terms_conditions`, ''), ':Other Terms Conditions:O:N:') as `other_terms_conditions`,
    concat(ifnull(`v`.`sales_order_status`, ''), ':Sales Order Status:O:N:') as `sales_order_status`,
    concat(ifnull(`v`.`sales_order_mail_sent_status`, ''), ':Sales Order Mail Sent Status:O:N:') as `sales_order_mail_sent_status`,
    concat(ifnull(`v`.`sales_order_acceptance_status`, ''), ':Sales Order Acceptance Status:O:N:') as `sales_order_acceptance_status`,
    concat(ifnull(`v`.`agent_paid_status`, ''), ':Agent Paid Status:O:N:') as `agent_paid_status`,
    concat(ifnull(`v`.`sales_order_type`, ''), ':Sales Order Type:O:N:') as `sales_order_type`,
    concat(ifnull(`v`.`sales_order_creation_type`, ''), ':Sales Order Creation Type:O:N:') as `sales_order_creation_type`,
    concat(ifnull(`v`.`is_freight_taxable`, ''), ':Is Freight Taxable:O:N:') as `is_freight_taxable`,
    concat(ifnull(`v`.`customer_email`, ''), ':Customer Email:O:N:') as `customer_email`,
    concat(ifnull(`v`.`customer_state_name`, ''), ':Customer State:O:N:') as `customer_state_name`,
    concat(ifnull(`v`.`customer_district_name`, ''), ':Customer District:O:N:') as `customer_district_name`,
    concat(ifnull(`v`.`customer_city_name`, ''), ':Customer City:O:N:') as `customer_city_name`,
    concat(ifnull(`v`.`consignee_state_name`, ''), ':Consignee State:O:N:') as `consignee_state_name`,
    concat(ifnull(`v`.`consignee_district_name`, ''), ':Consignee District:O:N:') as `consignee_district_name`,
    concat(ifnull(`v`.`consignee_city_name`, ''), ':Consignee City:O:N:') as `consignee_city_name`,
    concat(ifnull(`v`.`product_type_short_name`, ''), ':Product Type Short Name:O:N:') as `product_type_short_name`,
    concat(ifnull(`v`.`remark`, ''), ':Remark:O:N:') as `remark`,
    concat(ifnull(`v`.`company_name`, ''), ':Company Name:Y:C:cmv_company_summary:F') as `company_name`,
    concat(ifnull(`v`.`company_branch_name`, ''), ':Company Branch:Y:C:cmv_company_branch_summary:F') as `company_branch_name`,
    concat(ifnull(`v`.`financial_year`, ''), ':Financial Year:Y:C:amv_financial_year:F') as `financial_year`,
    concat(case when `v`.`is_active` = 1 then 'Active' else 'In Active' end, ':Active Status:Y:H:(Active, In Active)') as `Active`,
    concat(case when `v`.`is_delete` = 1 then 'Yes' else 'No' end, ':Deleted Status:Y:H:(Yes, No)') as `Deleted`,
    concat(ifnull(`v`.`created_by`, ''), ':Created By:O:N:') as `created_by`,
    concat(ifnull(`v`.`created_on`, ''), ':Modified On:O:N:') as `created_on`,
    concat(ifnull(`v`.`modified_by`, ''), ':Modified By:O:N:') as `modified_by`,
    concat(ifnull(`v`.`modified_on`, ''), ':Modified On:O:N:') as `modified_on`,
    concat(ifnull(`v`.`deleted_by`, ''), ':Deleted By:O:N:') as `deleted_by`,
    concat(ifnull(`v`.`deleted_on`, ''), ':Deleted On:O:N:') as `deleted_on`,
    concat(ifnull(`v`.`company_id`, ''), ':Company Id:N:N:') as `company_id`,
    concat(ifnull(`v`.`company_branch_id`, ''), ':Company Branch Id:N:N:') as `company_branch_id`,
    concat(ifnull(`v`.`sgst_percent`, ''), ':SGST Percent:N:N:') as `sgst_percent`,
    concat(ifnull(`v`.`igst_percent`, ''), ':IGST Percent:N:N:') as `igst_percent`,
    concat(ifnull(`v`.`cgst_percent`, ''), ':CGST Percent:N:N:') as `cgst_percent`,
    concat(ifnull(`v`.`sales_order_master_transaction_id`, ''), ':Sales Order Master Transaction Id:O:N:') as `sales_order_master_transaction_id`,
    concat(ifnull(`v`.`freight_hsn_code_id`, ''), ':Freight Hsn Code Id:N:N:') as `freight_hsn_code_id`,
    concat(ifnull(`v`.`sales_order_type_id`, ''), ':Sales Order Type Id:N:N:') as `sales_order_type_id`,
    concat(ifnull(`v`.`customer_id`, ''), ':Customer Id:N:N:') as `customer_id`,
    concat(ifnull(`v`.`customer_state_id`, ''), ':Customer State Id:N:N:') as `customer_state_id`,
    concat(ifnull(`v`.`customer_city_id`, ''), ':Customer City Id:N:N:') as `customer_city_id`,
    concat(ifnull(`v`.`consignee_id`, ''), ':Consignee Id:N:N:') as `consignee_id`,
    concat(ifnull(`v`.`consignee_state_id`, ''), ':Consignee State Id:N:N:') as `consignee_state_id`,
    concat(ifnull(`v`.`consignee_city_id`, ''), ':Consignee City Id:N:N:') as `consignee_city_id`,
    concat(ifnull(`v`.`department_id`, ''), ':Department Id:N:N:') as `department_id`,
    concat(ifnull(`v`.`approved_by_id`, ''), ':Approved By Id:N:N:') as `approved_by_id`,
    concat(ifnull(`v`.`agent_id`, ''), ':Agent Id:N:N:') as `agent_id`
from
    `mtv_sales_order_master_trading_summary` `v`
limit 1;
