
create or replace
algorithm = UNDEFINED view `ptv_mixing_chart_cotton_bales_rpt` as
select
    concat(ifnull(`v`.`mixing_chart_no`, ''), ':Mixing Chart No:Y:T:') as `mixing_chart_no`,
    concat(ifnull(`v`.`quality_testing_no`, ''), ':Quality Testing No:Y:T:') as `quality_testing_no`,
    concat(ifnull(`v`.`mixing_chart_date`, ''), ':Mixing Chart Date:Y:D:') as `mixing_chart_date`,
    concat(ifnull(`v`.`mixer_by_name`, ''), ':Mixer By Name:Y:T') as `mixer_by_name`,
    concat(ifnull(`v`.`plant_name`, ''), ':Plant Name:Y:T') as `plant_name`,
    concat(`v`.`batch_no`, ':Lot No:Y:T:') as `batch_no`,
    concat(`v`.`pr_no`, ':Pr No:Y:T:') as `pr_no`,
    concat(`v`.`uhml`, ':Uhml:O:N:') as `uhml`,
    concat(`v`.`ul`, ':Ul:O:N:') as `ul`,
    concat(`v`.`mi`, ':Mi:O:N:') as `mi`,
    concat(`v`.`mic`, ':Mic:O:N:') as `mic`,
    concat(`v`.`str`, ':Str:O:N:') as `str`,
    concat(`v`.`rd`, ':Rd:O:N:') as `rd`,
    concat(`v`.`b_plus`, ':B+:O:N:') as `b_plus`,
    concat(`v`.`total_neps`, ':Total Neps:O:N:') as `total_neps`,
    concat(`v`.`sc_n`, ':SC(N):O:N:') as `sc_n`,
    concat(`v`.`sfc_n`, ':SFC(N):O:N:') as `sfc_n`,
    concat(`v`.`trash`, ':TRASH:O:N:') as `trash`,
    concat(`v`.`moisture`, ':Moisture:O:N:') as `moisture`,
    concat(`v`.`cg`, ':CG:O:N:') as `cg`,
    concat(`v`.`issue_quantity`, ':Issued Qty.:O:N:') as `issue_quantity`,
    concat(`v`.`issue_weight`, ':Issued Wt.:O:N:') as `issue_weight`,
    concat(ifnull(`v`.`created_by`, ''), ':Created By:O:N:') as `created_by`,
    concat(ifnull(`v`.`created_on`, ''), ':Created On:O:N:') as `created_on`,
    concat(ifnull(`v`.`company_id`, ''), ':Company Id:N:N:') as `company_id`,
    concat(`v`.`issue_flag`, ':Issue Flag:O:N:') as `issue_flag`,
    concat(ifnull(`v`.`mixing_chart_cotton_bales_transaction_id`, ''), ': Mixing Chart Id:O:N:') as `mixing_chart_cotton_bales_transaction_id`
from
    `ptv_mixing_chart_cotton_bales` `v`
limit 1;


CREATE TABLE `pt_mixing_chart_standard_values` (
  `mixing_chart_standard_values_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `company_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session  ',
  `company_branch_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session ',
  `financial_year` varchar(20) NOT NULL,
  `mixing_chart_no` varchar(155) NOT NULL,
  `mixing_chart_date` date NOT NULL,
  `plant_id` bigint(20) NOT NULL,
  `mixing_by_id` bigint(20) NOT NULL,
  `max_uhml` decimal(18,4) DEFAULT 0.0000,
  `min_uhml` decimal(18,4) DEFAULT 0.0000,
  `max_ul` decimal(18,4) DEFAULT 0.0000,
  `min_ul` decimal(18,4) DEFAULT 0.0000,
  `max_mi` decimal(18,4) DEFAULT 0.0000,
  `min_mi` decimal(18,4) DEFAULT 0.0000,
  `max_mic` decimal(18,4) DEFAULT 0.0000,
  `min_mic` decimal(18,4) DEFAULT 0.0000,
  `max_str` decimal(18,4) DEFAULT 0.0000,
  `min_str` decimal(18,4) DEFAULT 0.0000,
  `max_rd` decimal(18,4) DEFAULT 0.0000,
  `min_rd` decimal(18,4) DEFAULT 0.0000,
  `max_b_plus` decimal(18,4) DEFAULT 0.0000,
  `min_b_plus` decimal(18,4) DEFAULT 0.0000,
  `max_total_neps` decimal(18,4) DEFAULT 0.0000,
  `min_total_neps` decimal(18,4) DEFAULT 0.0000,
  `max_sc_n` decimal(18,4) DEFAULT 0.0000,
  `min_sc_n` decimal(18,4) DEFAULT 0.0000,
  `max_sfc_n` decimal(18,4) DEFAULT 0.0000,
  `min_sfc_n` decimal(18,4) DEFAULT 0.0000,
  `max_trash` decimal(18,4) DEFAULT 0.0000,
  `min_trash` decimal(18,4) DEFAULT 0.0000,
  `max_moisture` decimal(18,4) DEFAULT 0.0000,
  `min_moisture` decimal(18,4) DEFAULT 0.0000,
  `is_active` bit(1) DEFAULT b'1',
  `is_delete` bit(1) DEFAULT b'0',
  `created_by` varchar(255) DEFAULT '1',
  `created_on` datetime DEFAULT NULL,
  `modified_by` varchar(255) DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  `deleted_on` datetime DEFAULT NULL,
  PRIMARY KEY (`mixing_chart_standard_values_id`)
);