-- sm_warping_bottom_stock_details definition

CREATE or replace TABLE `sm_warping_bottom_stock_details` (
  `company_id` int(11) DEFAULT 1 COMMENT '* Header part will come from Session *',
  `company_branch_id` bigint(20) DEFAULT 1 COMMENT '* Header part will come from Session *',
  `financial_year` varchar(20) NOT NULL COMMENT '* Header part will come from Session*',
  `warping_bottom_stock_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '* stock Details auto generated *',
  bottom_return_id bigint(20) DEFAULT 0 COMMENT '* bottom return id will come from return table *',
  bottom_return_no varchar(255) DEFAULT NULL,
  bottom_receipt_date date DEFAULT NULL,
  `set_no` varchar(250) DEFAULT NULL,
  `weaving_production_warping_bottom_details_id` bigint(20) DEFAULT 0,
  `weaving_production_warping_master_id` bigint(20) DEFAULT 0,
  `warping_production_code` varchar(255) NOT NULL,
  `warping_bottom_details_production_date` date NOT NULL,
  `creel_no` varchar(255) DEFAULT NULL,
  `no_of_package` decimal(18,2) DEFAULT 0,
  `gross_weight` decimal(18,2) DEFAULT 0,
  `net_weight` decimal(18,2) DEFAULT 0,
  `tare_weight` decimal(18,2) DEFAULT 0,
  `is_delete` bit(1) DEFAULT b'0',
  `package_type` varchar(255) DEFAULT NULL,
  `cone_type` varchar(100) DEFAULT NULL,
  `cone_type_value` decimal(18,4) DEFAULT 0.0000,
  `sr_no` varchar(255) DEFAULT NULL,
  `batch_no` varchar(255) DEFAULT NULL,
  `weight_per_pkg` decimal(18,4) DEFAULT NULL,
  `no_of_boxes` bigint(20) DEFAULT NULL,
  `product_material_id` varchar(55) DEFAULT NULL,
  stock_status varchar(3) DEFAULT 'A' COMMENT '* In Stock, Dispatch, Partial-Dispatch  *',
  dispatch_challan_no varchar(100) DEFAULT NULL,
  dispatch_challan_date date default NULL,
  godown_id bigint(20) NOT null,
  godown_section_id bigint(20) default null,
  godown_section_beans_id bigint(20) default null,
  customer_name varchar(255) default null,
  supplier_name varchar(255) default null,
  customer_id bigint(20) default null,
  supplier_id bigint(20) default null,
  `created_by` varchar(255) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `modified_by` varchar(255) DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  `deleted_on` datetime DEFAULT NULL,
  PRIMARY KEY (`warping_bottom_stock_id`)
);