-- cmv_supplier_rpt source

create or replace
algorithm = UNDEFINED view `cmv_supplier_rpt` as
select
    concat(`v`.`supplier_name`, ':Supplier Name:Y:T:') as `supplier_name`,
    concat(`v`.`supplier_short_name`, ':Supplier Short Name:O:N:') as `supplier_short_name`,
    concat(`v`.`supplier_sector`, ':Supplier Sector:O:N:') as `supplier_sector`,
    concat(`v`.`supplier_type`, ':Supplier Type:Y:C:cmv_supplier:O') as `supplier_type`,
    concat(`v`.`supplier_code`, ':Supplier Code:O:N:') as `supplier_code`,
    concat(`v`.`nature_of_business`, ':Nature Of Business:O:N:') as `nature_of_business`,
    concat(`v`.`supplier_payment_terms`, ':Payment Terms:Y:P:PaymentTermDays:') as `supplier_payment_terms`,
    concat(`v`.`supplier_rating`, ':Supplier Rating:Y:T:') as `supplier_rating`,
    concat(`v`.`supplier_gl_codes`, ':Supplier Gl Codes:O:N:') as `supplier_gl_codes`,
    concat(`v`.`supplier_history`, ':Supplier History:O:N:') as `supplier_history`,
    concat(`v`.`supp_branch_short_name`, ':Branch Short Name:O:N:') as `supp_branch_short_name`,
    concat(`v`.`supp_branch_address1`, ':Branch Address1:O:N:') as `supp_branch_address1`,
    concat(`v`.`supp_branch_address2`, ':Branch Address2:O:N:') as `supp_branch_address2`,
    concat(`v`.`supp_branch_pincode`, ':Branch Pincode:O:N:') as `supp_branch_pincode`,
    concat(`v`.`city_name`, ':City:Y:C:cmv_city:F') as `city_name`,
    concat(`v`.`district_name`, ':District:Y:C:cmv_district:F') as `district_name`,
    concat(`v`.`state_name`, ':State:Y:C:cmv_state:O') as `state_name`,
    concat(`v`.`country_name`, ':Country:Y:C:cmv_country:F') as `country_name`,
    concat(`v`.`supp_branch_region`, ':Branch Region:Y:P:Regions') as `supp_branch_region`,
    concat(`v`.`supp_branch_phone_no`, ':Branch Phone No:O:N:') as `supp_branch_phone_no`,
    concat(`v`.`supp_branch_cell_no`, ':Branch Cell No:O:N:') as `supp_branch_cell_no`,
    concat(`v`.`supp_branch_EmailId`, ':Branch EmailId:O:N:') as `supp_branch_EmailId`,
    concat(`v`.`supp_branch_website`, ':Branch Website:O:N:') as `supp_branch_website`,
    concat(`v`.`supp_branch_linkedin_profile`, ':Branch Linkedin Profile:O:N:') as `supp_branch_linkedin_profile`,
    concat(`v`.`supp_branch_twitter_profile`, ':Branch Twitter Profile:O:N:') as `supp_branch_twitter_profile`,
    concat(`v`.`supp_branch_facebook_profile`, ':Branch Facebook Profile:O:N:') as `supp_branch_facebook_profile`,
    concat(`v`.`supp_branch_gst_no`, ':Branch Gst No:O:N:') as `supp_branch_gst_no`,
    concat(`v`.`supp_branch_gst_division`, ':branch Gst Division:O:N:') as `supp_branch_gst_division`,
    concat(`v`.`supp_branch_gst_range`, ':Branch Gst Range:O:N:') as `supp_branch_gst_range`,
    concat(`v`.`supp_branch_pan_no`, ':Branch Pan No:O:N:') as `supp_branch_pan_no`,
    concat(`v`.`supp_branch_udyog_adhar_no`, ':Branch Udyog Adhar_no:O:N:') as `supp_branch_udyog_adhar_no`,
    concat(`v`.`supp_branch_vat_no`, ':Branch Vat No:O:N:') as `supp_branch_vat_no`,
    concat(`v`.`supp_branch_service_tax_no`, ':Branch Service Tax No:O:N:') as `supp_branch_service_tax_no`,
    concat(`v`.`supp_branch_excise_no`, ':Branch Excise No:O:N:') as `supp_branch_excise_no`,
    concat(`v`.`supp_branch_cst_no`, ':Branch Cst_no:O:N:') as `supp_branch_cst_no`,
    concat(`v`.`supp_branch_bst_no`, ':Branch Bst No:O:N:') as `supp_branch_bst_no`,
    concat(`v`.`supp_branch_tally_id`, ':Branch Tally_id:O:N:') as `supp_branch_tally_id`,
    concat(`v`.`supp_branch_rating`, ':Branch Rating:O:N:') as `supp_branch_rating`,
    concat(`v`.`supp_branch_gl_codes`, ':Branch Gl Codes:O:N:') as `supp_branch_gl_codes`,
    concat(`v`.`supp_branch_accounts_id`, ':Branch Accounts Id:O:N:') as `supp_branch_accounts_id`,
    concat(`v`.`is_sez`, ':Is Sez:Y:H:(Yes,No)') as `is_sez`,
    concat(`v`.`sez_name`, ':Sez Name:O:N:') as `sez_name`,
    concat(`v`.`company_name`, ':Company Name:Y:C:cmv_company_summary:F') as `company_name`,
    concat(`v`.`company_branch_name`, ':Company Branch Name:Y:C:cmv_company_branch_summary:F') as `company_branch_name`,
    concat(`v`.`remark`, ':Remark:O:N:') as `remark`,
    concat(case when `v`.`is_active` = 1 then 'Active' else 'In Active' end, ':Active Status:Y:H:(Active, In Active)') as `Active`,
    concat(case when `v`.`is_delete` = 1 then 'Yes' else 'No' end, ':Deleted Status:Y:H:(Yes, No)') as `Deleted`,
    concat(`v`.`created_by`, ':Created By:O:N:') as `created_by`,
    concat(`v`.`created_on`, ':Created On:O:N:') as `created_on`,
    concat(`v`.`modified_by`, ':Modified By:O:N:') as `modified_by`,
    concat(`v`.`modified_on`, ':Modified On:O:N:') as `modified_on`,
    concat(`v`.`deleted_by`, ':Deleted By:O:N:') as `deleted_by`,
    concat(`v`.`deleted_on`, ':Deleted On:O:N:') as `deleted_on`,
    concat(`v`.`company_id`, ':Company Id:N:N:') as `company_id`,
    concat(`v`.`company_branch_id`, ':Company Branch Id:N:N:') as `company_branch_id`,
    concat(`v`.`supplier_accounts_id`, ':Supplier Accounts Id:N:N:') as `supplier_accounts_id`,
    concat(`v`.`supplier_id`, ':Supplier Id:O:N:') as `supplier_id`,
    concat(`v`.`supp_branch_city_id`, ':Supp Branch City Id:N:N:') as `supp_branch_city_id`,
    concat(`v`.`supp_branch_district_id`, ':Supp Branch District Id:N:N:') as `supp_branch_district_id`,
    concat(`v`.`supp_branch_state_id`, ':Supp Branch State Id:N:N:') as `supp_branch_state_id`,
    concat(`v`.`supp_branch_country_id`, ':Supp Branch Country Id:N:N:') as `supp_branch_country_id`,
    concat(`v`.`supplier_id`, ':Supplier Id:N:N:') as `field_id`,
    concat(`v`.`supplier_name`, ':Supplier Name:N:N:') as `field_name`
from
    `cmv_supplier` `v`
limit 1;