-- ptv_grn_cotton_bales_details_rpt source

create or replace
algorithm = UNDEFINED view `ptv_grn_cotton_bales_details_rpt` as
select
    concat(ifnull(`v`.`goods_receipt_no`, ''), ':Goods Receipt No:Y:T') as `goods_receipt_no`,
    concat(ifnull(`v`.`goods_receipt_date`, ''), ':Goods Receipt Date:Y:D:') as `goods_receipt_date`,
    concat(ifnull(`v`.`goods_receipt_status`, ''), ':Grn Item Status:Y:H:(GRN,Done,Rejected,Partial Receipt,Completed,Canceled,Pree Closed)') as `goods_receipt_status`,
    concat(ifnull(`v`.`purchase_order_no`, ''), ':Purchase Order No:Y:T') as `purchase_order_no`,
    concat(ifnull(`v`.`purchase_order_date`, ''), ':Purchase Order Date:Y:D:') as `purchase_order_date`,
    concat(ifnull(`v`.`batch_no`, ''), ':Batch No:Y:T') as `batch_no`,
    concat(ifnull(`v`.`product_material_name`, ''), ':Material Name:Y:T') as `product_material_name`,
    concat(ifnull(`v`.`supplier_challan_no`, ''), ':Supplier Challan No:Y:C:ptv_goods_receipt_summary:O') as `supplier_challan_no`,
    concat(ifnull(`v`.`supplier_challan_date`, ''), ':Supplier Challan Date:Y:D:') as `supplier_challan_date`,
    concat(ifnull(`v`.`supplier_name`, ''), ':Supplier Name:Y:C:cmv_supplier:F') as `supplier_name`,
    concat(ifnull(`v`.`supplier_city_name`, ''), ':Supplier City Name:O:N:') as `supplier_city_name`,
    concat(ifnull(`v`.`supplier_state_name`, ''), ':Supplier State Name:Y:C:cmv_state:F') as `supplier_state_name`,
    concat(ifnull(`v`.`item_qa_by_id`, ''), ':Item QA By Id:O:N:') as `item_qa_by_id`,
    concat(ifnull(`v`.`item_qa_date`, ''), ':Item QA Date:Y:D:') as `item_qa_date`,
    concat(ifnull(`v`.`product_material_std_weight`, ''), ':Material Std Weight:O:N:') as `product_material_std_weight`,
    concat(ifnull(`v`.`product_material_stock_unit_name`, ''), ':Material Stock Unit Name:O:N:') as `product_material_stock_unit_name`,
    concat(ifnull(`v`.`product_material_po_approved_quantity`, ''), ':Material Po Approved Quantity:O:N:') as `product_material_po_approved_quantity`,
    concat(ifnull(`v`.`product_material_po_approved_weight`, ''), ':Material Po Approved Weight:O:N:') as `product_material_po_approved_weight`,
    concat(ifnull(`v`.`product_material_grn_quantity`, ''), ':Material GRN Quantity:O:N:') as `product_material_grn_quantity`,
    concat(ifnull(`v`.`product_material_grn_weight`, ''), ':Material GRN Weight:O:N:') as `product_material_grn_weight`,
    concat(ifnull(`v`.`material_rate`, ''), ':GRN Material Rate:O:N:') as `material_rate`,
    concat(ifnull(`v`.`grn_currency_name`, ''), ':GRN Currency Name:O:N:') as `grn_currency_name`,
    concat(ifnull(`v`.`material_basic_amount`, ''), ':Material Basic Amount:O:N:') as `material_basic_amount`,
    concat(ifnull(`v`.`material_discount_percent`, ''), ':Material Discount Percent:O:N:') as `material_discount_percent`,
    concat(ifnull(`v`.`material_discount_amount`, ''), ':Material Discount Amount:O:N:') as `material_discount_amount`,
    concat(ifnull(`v`.`material_taxable_amount`, ''), ':Material Taxable Amount:O:N:') as `material_taxable_amount`,
    concat(ifnull(`v`.`material_cgst_percent`, ''), ':Material Cgst Percent:O:N:') as `material_cgst_percent`,
    concat(ifnull(`v`.`material_cgst_total`, ''), ':Material Cgst Total:O:N:') as `material_cgst_total`,
    concat(ifnull(`v`.`material_sgst_percent`, ''), ':Material Sgst Percent:O:N:') as `material_sgst_percent`,
    concat(ifnull(`v`.`material_sgst_total`, ''), ':Material Sgst Total:O:N:') as `material_sgst_total`,
    concat(ifnull(`v`.`material_igst_percent`, ''), ':Material Igst Percent:O:N:') as `material_igst_percent`,
    concat(ifnull(`v`.`material_igst_total`, ''), ':Material Igst Total:O:N:') as `material_igst_total`,
    concat(ifnull(`v`.`material_total_amount`, ''), ':Material Total Amount:O:N:') as `material_total_amount`,
    concat(ifnull(`v`.`product_category1_name`, ''), ':Material Category1 Name:O:N:') as `product_category1_name`,
    concat(ifnull(`v`.`product_category2_name`, ''), ':Material Category2 Name:O:N:') as `product_category2_name`,
    concat(ifnull(`v`.`hsn_sac_code`, ''), ':Material Hsn Sac Code:O:N:') as `hsn_sac_code`,
    concat(ifnull(`v`.`hsn_sac_rate`, ''), ':Hsn Sac Rate:O:N:') as `hsn_sac_rate`,
    concat(ifnull(`v`.`excess_quantity`, ''), ':Excess Quantity:O:N:') as `excess_quantity`,
    concat(ifnull(`v`.`excess_weight`, ''), ':Excess Weight:O:N:') as `excess_weight`,
    concat(ifnull(`v`.`grn_item_status`, ''), ':Grn Item Status:O:N:') as `grn_item_status`,
    concat(ifnull(`v`.`press_running_no_from`, ''), ':Press No Running From:Y:T:') as `press_running_no_from`,
    concat(ifnull(`v`.`press_running_no_to`, ''), ':Press No Running To:Y:T:') as `press_running_no_to`,
    concat(ifnull(`v`.`company_name`, ''), ':Company Name:Y:C:cmv_company_summary:F') as `company_name`,
    concat(ifnull(`v`.`company_branch_name`, ''), ':Company Branch:Y:C:cmv_company_branch_summary:F') as `company_branch_name`,
    concat(ifnull(`v`.`financial_year`, ''), ':Financial Year:Y:C:amv_financial_year:F') as `financial_year`,
    concat(case when `v`.`is_delete` = 1 then 'Yes' else 'No' end, ':Deleted Status:Y:H:(Yes,No)') as `Deleted`,
    concat(ifnull(`v`.`created_by`, ''), ':Created By:O:N:') as `created_by`,
    concat(ifnull(`v`.`created_on`, ''), ':Modified On:O:N:') as `created_on`,
    concat(ifnull(`v`.`modified_by`, ''), ':Modified By:O:N:') as `modified_by`,
    concat(ifnull(`v`.`modified_on`, ''), ':Modified On:O:N:') as `modified_on`,
    concat(ifnull(`v`.`deleted_by`, ''), ':Deleted By:O:N:') as `deleted_by`,
    concat(ifnull(`v`.`deleted_on`, ''), ':Deleted On:O:N:') as `deleted_on`,
    concat(ifnull(`v`.`company_id`, ''), ':Company Id:N:N:') as `company_id`,
    concat(ifnull(`v`.`company_branch_id`, ''), ':Company Branch Id:N:N:') as `company_branch_id`,
    concat(ifnull(`v`.`department_id`, ''), ':Department Id:N:N:') as `department_id`,
    concat(ifnull(`v`.`grn_cotton_bales_details_transaction_id`, ''), 'grn_cotton_bales_details_transaction_id:N:N:') as `grn_cotton_bales_details_transaction_id`,
    concat(ifnull(`v`.`grn_cotton_bales_master_transaction_id`, ''), 'grn_cotton_bales_master_transaction_id:N:N:') as `grn_cotton_bales_master_transaction_id`,
    concat(ifnull(`v`.`product_material_unit_id`, ''), ':Material Unit Id:N:N:') as `product_material_unit_id`,
    concat(ifnull(`v`.`product_material_packing_id`, ''), ':Product Material Packing_id:N:N:') as `product_material_packing_id`,
    concat(ifnull(`v`.`product_material_hsn_code_id`, ''), ':Product Material Hsn Code_id:N:N:') as `product_material_hsn_code_id`,
    concat(ifnull(`v`.`goods_receipt_type_id`, ''), ':Goods Receipt Type Id:N:N:') as `goods_receipt_type_id`,
    concat(ifnull(`v`.`product_material_id`, ''), ':Product Material Id:N:N:') as `product_material_id`,
    concat(ifnull(`v`.`supplier_id`, ''), ':Supplier Id:N:N:') as `supplier_id`,
    concat(ifnull(`v`.`approved_by_id`, ''), ':Approved By:N:N:') as `approved_by_id`,
    concat(ifnull(`v`.`supplier_state_id`, ''), ':Supplier State Id:N:N:') as `supplier_state_id`,
    concat(ifnull(`v`.`supplier_city_id`, ''), ':Supplier City Id:N:N:') as `supplier_city_id`,
    concat(ifnull(`v`.`supplier_contacts_ids`, ''), ':Supplier Contacts Ids:N:N:') as `supplier_contacts_ids`,
    concat(ifnull(`v`.`expected_branch_id`, ''), ':Expected Branch Id:N:N:') as `expected_branch_id`,
    concat(ifnull(`v`.`expected_branch_state_id`, ''), ':Expected Branch State Id:N:N:') as `expected_branch_state_id`,
    concat(ifnull(`v`.`expected_branch_city_id`, ''), ':Expected Branch City Id:N:N:') as `expected_branch_city_id`,
    concat(ifnull(`v`.`payment_term_id`, ''), ':Payment Term Id:N:N:') as `payment_term_id`,
    concat(ifnull(`v`.`agent_id`, ''), ':Agent Id:N:N:') as `agent_id`,
    concat(ifnull(`v`.`product_category1_id`, ''), ':Product Category1 Id:N:N:') as `product_category1_id`,
    concat(ifnull(`v`.`product_category2_id`, ''), ':Product Category2 Id:N:N:') as `product_category2_id`,
    concat(ifnull(`v`.`goods_receipt_version`, ''), ':Goods Receipt Version:O:N:') as `goods_receipt_version`
from
    `ptv_grn_cotton_bales_details` `v`
limit 1;