-- erp_dev.mtv_dispatch_schedule_details_trading_rpt source

create or replace
algorithm = UNDEFINED view `mtv_dispatch_schedule_details_trading_rpt` as
select
    concat(`v`.`dispatch_schedule_no`, ':Dispatch Schedule No:Y:T:') as `dispatch_schedule_no`,
    concat(`v`.`dispatch_schedule_date`, ':Dispatch Schedule Date:Y:D:') as `dispatch_schedule_date`,
    concat(`v`.`dispatch_schedule_version`, ':Dispatch Schedule Version:O:N:') as `dispatch_schedule_version`,
    concat(`v`.`customer_order_no`, ':Customer Order No:Y:T:') as `customer_order_no`,
    concat(`v`.`dispatch_schedule_type`, ':Dispatch Schedule Type:Y:T:') as `dispatch_schedule_type`,
    concat(`v`.`dispatch_schedule_item_status`, ':Dispatch Schedule Item Status:Y:H:(Pending,Aprroved,Rejected,Partial Sales Issue,Completed,Canceled,Dispath Challan Created,Invoice Created,Pending)') as `dispatch_schedule_item_status_desc`,
    concat(`v`.`product_material_print_name`, ':Product Name:Y:T:') as `product_material_print_name`,
    concat(`v`.`product_material_code`, ':Product Code:Y:T:') as `product_material_code`,
    concat(`v`.`expected_dispatch_quantity`, ':Dispatch Quantity:O:N:') as `expected_dispatch_quantity`,
    concat(`v`.`actual_dispatch_quantity`, ':Actual Dispatch Quantity:O:N:') as `actual_dispatch_quantity`,
    concat(`v`.`customer_order_Date`, ':Customer Order Date:Y:D:') as `customer_order_Date`,
    concat(`v`.`dispatch_return_quantity`, ':Dispatch Return Quantity:O:N:') as `dispatch_return_quantity`,
    concat(`v`.`expected_schedule_date`, ':Expected Schedule Date:Y:D:') as `expected_schedule_date`,
    concat(`v`.`delayed_days`, ':Delayed Days:O:N:') as `delayed_days`,
    concat(`v`.`dispatched_quantity`, ':Dispatched Quantity:O:N:') as `dispatched_quantity`,
    concat(`v`.`dispatched_weight`, ':Dispatched Weight:O:N:') as `dispatched_weight`,
    concat(`v`.`dispatch_schedule_creation_type`, ':Dispatch Schedule Creation Type:Y:H:(Closed,Open)') as `dispatch_schedule_creation_type`,
    concat(`v`.`dispatch_schedule_item_status`, ':Dispatch Schedule Item Status:O:N:') as `dispatch_schedule_item_status`,
    concat(`v`.`dispatch_schedule_remark`, ':Dispatch Schedule Remark:O:N:') as `dispatch_schedule_remark`,
    concat(`v`.`approved_date`, ':Approved Date:Y:D:') as `approved_date`,
    concat(`v`.`total_quantity`, ':Total Quantity:O:N:') as `total_quantity`,
    concat(`v`.`actual_quantity`, ':Actual Quantity:O:N:') as `actual_quantity`,
    concat(`v`.`so_sr_no`, ':So Sr No:O:N:') as `so_sr_no`,
    concat(`v`.`batch_no`, ':Batch No:O:N:') as `batch_no`,
    concat(`v`.`dispatch_note_status`, ':Dispatch Note Status:O:N:') as `dispatch_note_status`,
    concat(`v`.`dispatch_note_remark`, ':Dispatch Note Remark:O:N:') as `dispatch_note_remark`,
    concat(`v`.`other_terms_conditions`, ':Other Terms Conditions:O:N:') as `other_terms_conditions`,
    concat(`v`.`remark`, ':Remark:O:N:') as `remark`,
    concat(`v`.`company_name`, ':Company Name:Y:C:cmv_company_summary:F') as `company_name`,
    concat(`v`.`company_branch_name`, ':Company Branch Name:Y:C:cmv_company_branch_summary:F') as `company_branch_name`,
    concat(`v`.`financial_year`, ':Financial Year:O:N:') as `financial_year`,
    concat(case when `v`.`is_active` = 1 then 'Active' else 'In Active' end, ':Active Status:Y:H:(Active, In Active)') as `Active`,
    concat(case when `v`.`is_delete` = 1 then 'Yes' else 'No' end, ':Deleted Status:Y:H:(Yes, No)') as `Deleted`,
    concat(`v`.`created_by`, ':Created By:O:N:') as `created_by`,
    concat(`v`.`created_on`, ':Created On:O:N:') as `created_on`,
    concat(`v`.`modified_by`, ':Modified By:O:N:') as `modified_by`,
    concat(`v`.`modified_on`, ':Modified On:O:N:') as `modified_on`,
    concat(`v`.`deleted_by`, ':Deleted By:O:N:') as `deleted_by`,
    concat(`v`.`deleted_on`, ':Deleted On:O:N:') as `deleted_on`,
    concat(`v`.`company_id`, ':Company Id:N:N:') as `company_id`,
    concat(`v`.`company_branch_id`, ':Company Branch Id:N:N:') as `company_branch_id`,
    concat(`v`.`product_material_id`, ':Product Material Id:N:N:') as `product_material_id`,
    concat(`v`.`product_material_unit_id`, ':Product Material Unit Id:N:N:') as `product_material_unit_id`,
    concat(`v`.`product_material_packing_id`, ':Material Packing Id:N:N:') as `product_material_packing_id`,
    concat(`v`.`dispatch_schedule_type_id`, ':Dispatch Schedule Type Id:N:N:') as `dispatch_schedule_type_id`,
    concat(`v`.`dispatch_schedule_master_transaction_id`, ':Dispatch Schedule Master Transaction Id:O:N:') as `dispatch_schedule_master_transaction_id`,
    concat(`v`.`dispatch_schedule_details_transaction_id`, ':Dispatch Schedule Details Transaction Id:N:N:') as `dispatch_schedule_details_transaction_id`,
    concat(`v`.`customer_id`, ':Customer Id:N:N:') as `customer_id`,
    concat(`v`.`customer_contacts_ids`, ':Customer Contacts Ids:N:N:') as `customer_contacts_ids`,
    concat(`v`.`customer_state_id`, ':Customer State Id:N:N:') as `customer_state_id`,
    concat(`v`.`customer_city_id`, ':Customer City Id:N:N:') as `customer_city_id`,
    concat(`v`.`consignee_id`, ':Consignee Id:N:N:') as `consignee_id`,
    concat(`v`.`consignee_state_id`, ':Consignee State Id:N:N:') as `consignee_state_id`,
    concat(`v`.`consignee_city_id`, ':Consignee City Id:N:N:') as `consignee_city_id`,
    concat(`v`.`dispatch_supervisor_id`, ':Dispatch Supervisor Id:N:N:') as `dispatch_supervisor_id`,
    concat(`v`.`approved_by_id`, ':Approved By Id:N:N:') as `approved_by_id`
from
    `mtv_dispatch_schedule_details_trading` `v`
limit 1;