


CREATE TABLE `pt_goods_return_fabric_master` (
  `goods_return_fabric_master_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '* Header part read only back end auto generated *',
  `company_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*backend from session  ',
  `company_branch_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '*combo box with cmv_company_branch  and set default backend from session  *',
  `financial_year` varchar(20) NOT NULL COMMENT '*backend from session  ',
  `goods_return_fabric_no` varchar(50) NOT NULL COMMENT '1/1 * Header part read only text box Combination of Company Short name/FyearShort name/ProductType_group / GR0000Last ID ',
  `goods_return_fabric_date` date NOT NULL COMMENT '1/1/2* Header part  DTPpicker Data Entry set todays date ',
  `goods_return_fabric_version` bigint(20) NOT NULL DEFAULT 1 COMMENT '* 1/1/3 Header part read only text box auto generated next Version *',
  `supplier_id` bigint(20) DEFAULT NULL COMMENT '* 1/2 Header part combo box with cmv_supllier show address, Contact person list ,emails, supplier state combo,supplier city Combo ',
  `supplier_state_id` bigint(20) DEFAULT NULL COMMENT '* 1/3 Header part read only combo box with cmv_state show will change on selection of supllier combo ',
  `supplier_city_id` bigint(20) DEFAULT NULL COMMENT '* 1/4 Header part read only  combo box with cmv_city show will change on selection of supllier combo ',
  `supplier_contacts_ids` varchar(1000) DEFAULT NULL COMMENT '* 1/5  Header part read only  grid data show all supplier details saved in purchase order  will change on selection of supllier combo and saved in supplier_contact_id concanitate with :',
  `expected_branch_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '* 2/2  Header part read only combo box fill with cmv_company_branch  and set on purchase order _combo selection from ptv_purchase_order_Details   *',
  `expected_branch_state_id` bigint(20) DEFAULT NULL COMMENT '* 2/3   Header part read only  combo box fill with cmv_state and set on purchase order _combo selection from ptv_purchase_order_Details   ',
  `expected_branch_city_id` bigint(20) DEFAULT NULL COMMENT ' * 2/4  Header part read only  combo box fill with cmv_city show and set on purchase order _combo selection from ptv_purchase_order_Details  ',
  `goods_return_fabric_type_id` bigint(20) DEFAULT 2 COMMENT ' * 2/5/1  Header part read only read only combo box with cmv_product_type  and set on purchase order _combo selection from ptv_purchase_order_Details  ',
  `goods_return_fabric_type` varchar(100) DEFAULT NULL COMMENT '2/5/2 * Header part read only  text box will set purchase_order_no combos selected from ptv_purchase_order_Details     and save product group ',
  `supplier_challan_no` varchar(500) DEFAULT NULL COMMENT '* 1/9/1  Header part text box data entry ',
  `supplier_challan_date` date NOT NULL COMMENT '* 1/9/2  Header part  DTPpicker data entry ',
  `approved_by_id` bigint(20) DEFAULT NULL COMMENT '  2/8/1 *  Header part combo box with cmv_employee with department id and deaprtment head filter  and set on purchase order _combo selection from ptv_purchase_order_Details ',
  `approved_date` date DEFAULT NULL COMMENT '2/8/2* combo box with dtppicker data entry  and set on purchase order _combo selection from ptv_purchase_order_Details ',
  `qa_by_id` bigint(20) DEFAULT NULL COMMENT '  2/9/1 *  Header part combo box with cmv_employee with department id ',
  `qa_date` date DEFAULT NULL COMMENT '2/9/2* combo box with dtppicker data entry   ',
  `basic_total` decimal(18,2) DEFAULT 0.00 COMMENT ' 1/1 *  footer part read only text box with all realeted sum',
  `is_freight_taxable` bit(1) DEFAULT b'0' COMMENT '1/3/2    footer part  check box   ',
  `transport_amount` decimal(18,4) DEFAULT 0.0000 COMMENT '1/2    footer part  text box with data entry and numeric validation on chenge if is_freight_taxable selected calculate CGST & SGST /IGST as per states & Tax calcualtion logic and add that ',
  `freight_amount` decimal(18,4) DEFAULT 0.0000 COMMENT '1/3/1    footer part  text box with data entry and numeric validation',
  `freight_hsn_code_id` bigint(20) DEFAULT NULL,
  `packing_amount` decimal(18,4) DEFAULT 0.0000 COMMENT '1/4  footer part   text box with data entry and numeric validation',
  `goods_return_discount_percent` decimal(18,4) DEFAULT 0.0000 COMMENT '1/5/1   footer part  text box with data entry and on change calculates po_discount_amount and numeric validation',
  `goods_return_discount_amount` decimal(18,4) DEFAULT 0.0000 COMMENT '1/5/2   footer part   text box with data entry and on change calculates po_discount_percent and numeric validation',
  `other_amount` decimal(18,4) DEFAULT 0.0000 COMMENT '1/6  footer part   text box with data entry and numeric validation',
  `taxable_total` decimal(18,4) DEFAULT 0.0000 COMMENT '1/7  footer part read only text box ( auto calcualted formulla Basic Total-Discount AMount)   and numeric validation',
  `cgst_total` decimal(18,4) DEFAULT 0.0000 COMMENT '* 2/1   footer part read only text box with sum of all realeted values cgst_amount cloumn in Detail Grid ',
  `sgst_total` decimal(18,4) DEFAULT 0.0000 COMMENT '* 2/2   footer part read only text box with sum of all realeted values sgst_amount cloumn in Detail Grid ',
  `igst_total` decimal(18,4) DEFAULT 0.0000 COMMENT '* 2/3   footer part read only text box with sum of all realeted values igst_amount cloumn in Detail Grid ',
  `grand_total` decimal(18,4) DEFAULT 0.0000 COMMENT '2/4/1  footer part read only text box ( auto calcualted formulla Basic Total-Discount AMount)   and numeric validation',
  `roundoff` decimal(18,4) DEFAULT 0.0000 COMMENT '2/4/2  footer part read only text box ( auto calcualted formulla  round up diffrance of grand Total  )   and numeric validation',
  `agent_id` bigint(20) DEFAULT NULL COMMENT '2/5/1  footer part read only combo box fill with cmv_customer show address, Contact person list ,emails, customer state combo,customer city Combo and set on purchase order _combo selection from ptv_purchase_order_Details ',
  `agent_percent` decimal(18,4) DEFAULT 0.0000 COMMENT '2/6/1  footer part read only  text box with data entry and numeric validation and set on purchase order _combo selection from ptv_purchase_order_Details',
  `agent_paid_status` varchar(1) DEFAULT 'P' COMMENT ' 2/6/2  footer part read only redio button  P-Pending,A-Aprroved,  C-Completed, X-Canceled  will changes according to trnasaction  done ',
  `goods_return_fabric_status` varchar(1) DEFAULT 'P' COMMENT '  2/7  footer part read only combo G-GRN Done, Q-QC Done, R-Rejected,I-Partial Receipt, C-Completed, X-Canceled  will changes according to trnasactions  done ',
  `lr_no` varchar(100) DEFAULT NULL COMMENT '3/2/1  footer part   text box with data entry  ',
  `lr_date` date DEFAULT NULL COMMENT ' 3/2/2  footer part     dtppicker   Data entry ',
  `vehicle_no` varchar(100) DEFAULT NULL COMMENT '3/3  footer part   text box with data entry  ',
  `other_terms_conditions` varchar(1000) DEFAULT NULL COMMENT '3/4  footer part   text box with data entry and set on purchase order _combo selection from ptv_purchase_order_Details ',
  `is_preeclosed` bit(1) DEFAULT b'0',
  `remark` varchar(1000) DEFAULT NULL COMMENT '3/5 footer part   text box with data entry and set on purchase order _combo selection from ptv_purchase_order_Details  ',
  `is_active` bit(1) DEFAULT b'1' COMMENT '3/6  footer part   check box with data entry  ',
  `is_delete` bit(1) DEFAULT b'0' COMMENT '*backend from deleted  slection  ',
  `created_by` varchar(255) DEFAULT '1' COMMENT '*backend from session user id  ',
  `created_on` datetime DEFAULT NULL COMMENT '*backend from session server current date time   ',
  `modified_by` varchar(255) DEFAULT NULL COMMENT '*backend from session user id when update functionality done only  ',
  `modified_on` datetime DEFAULT NULL COMMENT '*backend from session server current date time when update functionality done only  ',
  `deleted_by` varchar(255) DEFAULT NULL COMMENT '*backend from session user id when delete functionality done only  ',
  `deleted_on` datetime DEFAULT NULL COMMENT '*backend from session server current date time when delete functionality done only  ',
  `supplier_invoice_no` varchar(50) DEFAULT NULL,
  `supplier_invoice_date` date DEFAULT NULL,
  `ev_bill_no` varchar(50) DEFAULT NULL,
  `ev_bill_date` date DEFAULT NULL,
  `purchase_type` varchar(100) DEFAULT NULL,
  `goods_purchase_type` varchar(100) DEFAULT NULL,
  `goods_purchase_tax_type` varchar(100) DEFAULT NULL,
  `goods_purchase_sales_type` varchar(100) DEFAULT NULL,
  `goods_purchase_voucher_type` varchar(100) DEFAULT NULL,
  `fabric_type` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`goods_return_fabric_master_id`)
);


CREATE TABLE `pt_goods_return_fabric_details` (
  `goods_return_fabric_details_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '* will used from  Header part data',
  `goods_return_fabric_master_id` bigint(20) NOT NULL,
  `company_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '* will used from  Header part data',
  `company_branch_id` bigint(20) NOT NULL DEFAULT 1 COMMENT '* will used from  Header part data',
  `financial_year` varchar(20) NOT NULL COMMENT '* will used from  Header part data ',
  `goods_return_fabric_no` varchar(50) NOT NULL COMMENT ' * will used from  Header part data',
  `goods_return_fabric_date` date NOT NULL COMMENT '* will used from  Header part data ',
  `goods_return_fabric_version` bigint(20) NOT NULL DEFAULT 1 COMMENT '* will used from  Header part data',
  `item_qa_by_id` bigint(20) DEFAULT NULL COMMENT '    *  Details data grid   combo box with cmv_employee with department id  and set header part  Qa by id by default',
  `item_qa_date` date DEFAULT NULL COMMENT 'Details data grid  dtppicker data entry  and set header part  Qa  Date by default  ',
  `goods_return_fabric_type_id` bigint(20) DEFAULT 2 COMMENT ' * Details part Data Grid Entry  with Export/Import excel combo box with cmv_product_type  and set on purchase order _combo selection from ptv_purchase_order_Details  ',
  `goods_return_fabric_type` varchar(100) DEFAULT NULL COMMENT ' * Details part  Data  Grid Entry  with Export/Import excel  text box will set purchase_order_no combos selected from ptv_purchase_order_Details     and save product group ',
  `sort_no` varchar(50) DEFAULT NULL,
  `product_material_id` varchar(20) DEFAULT NULL COMMENT '* Details Part Data Grid Entry  with Export/Import excel format  combo box with cmv_product_rm/cmv_product_fg/cmv_product_sr with all technical parameter shows ing grids for selected material / and set on purchase order _combo selection from ptv_purchase_order_Details ',
  `product_material_name` varchar(1000) DEFAULT NULL COMMENT '* Details Part Data Grid Entry  with Export/Import excel format  text box with techinacal Specification shows ing grids for selected material and set on purchase order _combo selection from ptv_purchase_order_Details ',
  `product_material_unit_id` bigint(20) DEFAULT NULL COMMENT '* Details Part Data Grid  with Export/Import excel format Entry combo box with cmv_unit  and set on purchase order _combo selection from ptv_purchase_order_Details ',
  `product_material_packing_id` bigint(20) DEFAULT NULL COMMENT '* Details Part Data Grid  with Export/Import excel format Entry combo box with cmv_Packing and set on purchase order _combo selection from ptv_purchase_order_Details',
  `product_material_hsn_code_id` bigint(20) DEFAULT NULL COMMENT '* Details Part Data Grid  with Export/Import excel format Entry combo box with cmv_hsn_csac and set on purchase order _combo selection from ptv_purchase_order_Details ',
  `product_goods_return_quantity` decimal(18,4) DEFAULT 1.0000 COMMENT '* Details Part Data Grid  with Export/Import excel format Entry txtbox data entry with validation / and set on purchase order _combo selection from ptv_purchase_order_Details  ',
  `product_goods_return_weight` decimal(18,4) DEFAULT 1.0000 COMMENT '* Details Part Data Grid  with Export/Import excel format Entry txtbox data entry with validation / and set on purchase order _combo selection from ptv_purchase_order_Details   ',
  `product_return_no_of_rolls` bigint(20) DEFAULT 0,
  `goods_return_currency_id` bigint(20) DEFAULT 3 COMMENT 'default grn currency is rupees',
  `product_material_conversion_factor` decimal(18,4) DEFAULT 1.0000 COMMENT '* Details Part Data Grid  with Export/Import excel format Entry txtbox will come from munit convert it to Basic Stock Unit  with validation /and set on purchase order _combo selection from ptv_purchase_order_Details ',
  `currency_id` bigint(20) DEFAULT 3 COMMENT 'default rupees given',
  `material_rate` decimal(18,4) DEFAULT 1.0000 COMMENT '* Data Grid  with Export/Import excel format Entry txtbox data entry with validation  / Show last Purchase rate by default',
  `currency_exchange_rate` decimal(18,4) DEFAULT 0.0000 COMMENT 'exchange rate of base currency INR',
  `material_basic_amount` decimal(18,4) DEFAULT 1.0000 COMMENT '* Data Grid  with Export/Import excel format Entry txtbox caculation rate* quantity with validation ',
  `material_freight_amount` decimal(18,4) DEFAULT NULL,
  `material_discount_percent` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry txtbox data entry with validation ',
  `material_discount_amount` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry txtbox caculation basic_amount* discount percent with validation ',
  `material_taxable_amount` decimal(18,4) DEFAULT 1.0000 COMMENT '* Data Grid  with Export/Import excel format Entry txtbox caculation basic_amount- discount amount with validation ',
  `material_cgst_percent` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry txtbox data on the basis of HSN Code & Customer Stae code with validation ',
  `material_cgst_total` decimal(18,4) DEFAULT 0.0000 COMMENT '*  text box with caculation taxable_amount * cgst Percent percent and numeric validation',
  `material_sgst_percent` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry txtbox data on the basis of HSN Code & Customer Stae code with validation ',
  `material_sgst_total` decimal(18,4) DEFAULT 0.0000 COMMENT '*  text box with caculation taxable_amount * sgst Percent percent and numeric validation',
  `material_igst_percent` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry txtbox data on the basis of HSN Code & Customer Stae code with validation ',
  `material_igst_total` decimal(18,4) DEFAULT 0.0000 COMMENT '*  text box with caculation taxable_amount * igst Percent percent and numeric validation',
  `material_total_amount` decimal(18,4) DEFAULT 0.0000 COMMENT '* Data Grid  with Export/Import excel format Entry txtbox caculation taxable Amount +GST Amount+ SGst Amount + IGstAmount  with validation ',
  `goods_return_fabric_product_status` varchar(1) DEFAULT 'P' COMMENT 'combo G-GRN Done, Q-QC Done, R-Rejected,I-Partial Receipt, C-Completed, X-Canceled Z-PreeClosed  will changes according to trnasactions  done  ',
  `godown_id` bigint(20) DEFAULT NULL,
  `godown_section_id` bigint(20) DEFAULT NULL,
  `godown_section_beans_id` bigint(20) DEFAULT NULL,
  `remark` varchar(1000) DEFAULT NULL COMMENT '3/5 footer part   text box with data entry and set on purchase order _combo selection from ptv_purchase_order_Details  ',
  `is_active` bit(1) DEFAULT b'1' COMMENT '3/6  footer part   check box with data entry  ',
  `is_delete` bit(1) DEFAULT b'0' COMMENT '*backend from deleted  slection  ',
  `created_by` varchar(255) DEFAULT '1' COMMENT '*backend from session user id  ',
  `created_on` datetime DEFAULT NULL COMMENT '*backend from session server current date time   ',
  `modified_by` varchar(255) DEFAULT NULL COMMENT '*backend from session user id when update functionality done only  ',
  `modified_on` datetime DEFAULT NULL COMMENT '*backend from session server current date time when update functionality done only  ',
  `deleted_by` varchar(255) DEFAULT NULL COMMENT '*backend from session user id when delete functionality done only  ',
  `deleted_on` datetime DEFAULT NULL COMMENT '*backend from session server current date time when delete functionality done only  ',
  PRIMARY KEY (`goods_return_fabric_details_id`)
) ;