-- ptv_purchase_order_master_summary_rpt source

CREATE OR REPLACE
ALGORITHM = UNDEFINED VIEW `ptv_purchase_order_master_summary_rpt` AS
select
    concat(ifnull(`v`.`purchase_order_no`, ''), ':Purchase Order No:Y:T') AS `purchase_order_no`,
    concat(ifnull(`v`.`purchase_order_version`, ''), ':Purchase Order Version:O:N:') AS `purchase_order_version`,
    concat(ifnull(`v`.`purchase_order_date`, ''), ':Purchase Order Date:Y:D:') AS `purchase_order_date`,
    concat(ifnull(`v`.`purchase_order_status`, ''), ':Purchase Order Status:Y:H:(Approved,Rejected,Partial Receipt,Completed,Canceled,Pree Closed,Pending)') AS `purchase_order_status_desc`,
    concat(ifnull(`v`.`supplier_name`, ''), ':Supplier Name:Y:T') AS `supplier_name`,
    concat(ifnull(`v`.`basic_total`, ''), ':Basic Total:O:N:') AS `basic_total`,
    concat(ifnull(`v`.`transport_amount`, ''), ':Transport Amount:O:N:') AS `transport_amount`,
    concat(ifnull(`v`.`freight_amount`, ''), ':Freight Amount:O:N:') AS `freight_amount`,
    concat(ifnull(`v`.`is_freight_taxable`, ''), ':Is Freight Taxable:O:N:') AS `is_freight_taxable`,
    concat(ifnull(`v`.`packing_amount`, ''), ':Packing Amount:O:N:') AS `packing_amount`,
    concat(ifnull(`v`.`po_discount_percent`, ''), ':PO Discount Percent:O:N:') AS `po_discount_percent`,
    concat(ifnull(`v`.`po_discount_amount`, ''), ':PO Discount Amount:O:N:') AS `po_discount_amount`,
    concat(ifnull(`v`.`other_amount`, ''), ':Other Amount:O:N:') AS `other_amount`,
    concat(ifnull(`v`.`taxable_total`, ''), ':Taxable Total:O:N:') AS `taxable_total`,
    concat(ifnull(`v`.`cgst_total`, ''), ':CGST Total:O:N:') AS `cgst_total`,
    concat(ifnull(`v`.`sgst_total`, ''), ':SGST Total:O:N:') AS `sgst_total`,
    concat(ifnull(`v`.`igst_total`, ''), ':IGST Total:O:N:') AS `igst_total`,
    concat(ifnull(`v`.`roundoff`, ''), ':RoundOff:O:N:') AS `roundoff`,
    concat(ifnull(`v`.`grand_total`, ''), ':Grand Total:O:N:') AS `grand_total`,
    concat(ifnull(`v`.`quotation_no`, ''), ':Quotation No:Y:T') AS `quotation_no`,
    concat(ifnull(`v`.`quotation_date`, ''), ':Quotation Date:Y:D:') AS `quotation_date`,
    concat(ifnull(`v`.`approved_by`, ''), ':Approved By:Y:C:cmv_employee_list:F') AS `approved_by`,
    concat(ifnull(`v`.`approved_date`, ''), ':Approved Date:Y:D:') AS `approved_date`,
    concat(ifnull(`v`.`expected_schedule_date`, ''), ':Expected Schedule Date:Y:D:') AS `expected_schedule_date`,
    concat(ifnull(`v`.`purchase_order_acceptance_status`, ''), ':Purchase Order Acceptance Status:Y:H:(Approved,Canceled,Pending)') AS `purchase_order_acceptance_status_desc`,
    concat(ifnull(`v`.`purchase_order_mail_sent_status`, ''), ':Mail Sent Status:Y:H:(Email Sent,Email Failed,Email Pending)') AS `purchase_order_mail_sent_status_desc`,
    concat(ifnull(`v`.`purchase_order_creation_type_desc`, ''), ':Purchase Order Creation Type:Y:H:(Manual,Auto)') AS `purchase_order_creation_type_desc`,
    concat(ifnull(`v`.`purchase_order_life_desc`, ''), ':Purchase Order Life:Y:H:(Close,Open)') AS `purchase_order_life_desc`,
    concat(ifnull(`v`.`status_remark`, ''), ':Status Remark:O:N:') AS `status_remark`,
    concat(ifnull(`v`.`supplier_code`, ''), ':Supplier Code:O:N:') AS `supplier_code`,
    concat(ifnull(`v`.`supplier_type`, ''), ':Supplier Type:O:N:') AS `supplier_type`,
    concat(ifnull(`v`.`supplier_short_name`, ''), ':Supplier Short Name:O:N:') AS `supplier_short_name`,
    concat(ifnull(`v`.`supp_branch_address1`, ''), ':Branch Address1:O:N:') AS `supp_branch_address1`,
    concat(ifnull(`v`.`supp_branch_pincode`, ''), ':Branch Pincode:O:N:') AS `supp_branch_pincode`,
    concat(ifnull(`v`.`city_name`, ''), ':City Name:O:N:') AS `city_name`,
    concat(ifnull(`v`.`district_name`, ''), ':District Name:O:N:') AS `district_name`,
    concat(ifnull(`v`.`state_name`, ''), ':State Name:O:N:') AS `state_name`,
    concat(ifnull(`v`.`supp_branch_phone_no`, ''), ':Branch Phone No:O:N:') AS `supp_branch_phone_no`,
    concat(ifnull(`v`.`supp_branch_EmailId`, ''), ':Branch EmailId:O:N:') AS `supp_branch_EmailId`,
    concat(ifnull(`v`.`expected_branch_name`, ''), ':Branch Name:O:N:') AS `expected_branch_name`,
    concat(ifnull(`v`.`expected_branch_short_name`, ''), ':Branch Short Name:O:N:') AS `expected_branch_short_name`,
    concat(ifnull(`v`.`expected_branch_address1`, ''), ':Branch Address1:O:N:') AS `expected_branch_address1`,
    concat(ifnull(`v`.`expected_branch_pincode`, ''), ':Branch Pincode:O:N:') AS `expected_branch_pincode`,
    concat(ifnull(`v`.`expected_branch_city_name`, ''), ':Branch City Name:O:N:') AS `expected_branch_city_name`,
    concat(ifnull(`v`.`expected_branch_district_name`, ''), ':Branch District Name:O:N:') AS `expected_branch_district_name`,
    concat(ifnull(`v`.`expected_branch_state_name`, ''), ':Branch State Name:O:N:') AS `expected_branch_state_name`,
    concat(ifnull(`v`.`expected_branch_phone_no`, ''), ':Branch Phone No:O:N:') AS `expected_branch_phone_no`,
    concat(ifnull(`v`.`expected_branch_EmailId`, ''), ':Expected Branch EmailId:O:N:') AS `expected_branch_EmailId`,
    concat(ifnull(`v`.`agent_name`, ''), ':Agent Name:Y:C:cmv_agent:F') AS `agent_name`,
    concat(ifnull(`v`.`agent_percent`, ''), ':Agent Percent:O:N:') AS `agent_percent`,
    concat(ifnull(`v`.`agent_paid_status`, ''), ':Agent Paid Status:Y:H:(Approved,Completed,Canceled,Pending)') AS `agent_paid_status_desc`,
    concat(ifnull(`v`.`other_terms_conditions`, ''), ':Other Terms Conditions:O:N:') AS `other_terms_conditions`,
    concat(ifnull(`v`.`remark`, ''), ':Remark:O:N:') AS `remark`,
    concat(ifnull(`v`.`product_type_short_name`, ''), ':Product Type Short Name:O:N:') AS `product_type_short_name`,
    concat(ifnull(`v`.`hsn_sac_code`, ''), ':Freight Hsn Sac Code:O:N:') AS `hsn_sac_code`,
    concat(ifnull(`v`.`hsn_sac_rate`, ''), ':Freight Hsn Sac Rate:O:N:') AS `hsn_sac_rate`,
    concat(ifnull(case when `v`.`is_active` = 1 then 'Active' else 'In Active' end, ''), ':Active Status:Y:H:(Active,In Active)') AS `Active`,
    concat(ifnull(case when `v`.`is_delete` = 1 then 'Yes' else 'No' end, ''), ':Deleted Status:Y:H:(Yes,No)') AS `Deleted`,
    concat(ifnull(`v`.`created_by`, ''), ':Created By:O:N:') AS `created_by`,
    concat(ifnull(`v`.`created_on`, ''), ':Modified On:O:N:') AS `created_on`,
    concat(ifnull(`v`.`modified_by`, ''), ':Modified By:O:N:') AS `modified_by`,
    concat(ifnull(`v`.`modified_on`, ''), ':Modified On:O:N:') AS `modified_on`,
    concat(ifnull(`v`.`deleted_by`, ''), ':Deleted By:O:N:') AS `deleted_by`,
    concat(ifnull(`v`.`deleted_on`, ''), ':Deleted On:O:N:') AS `deleted_on`,
    concat(ifnull(`v`.`purchase_order_master_transaction_id`, ''), ':Purchase Order Master Transaction_id:O:N:') AS `purchase_order_master_transaction_id`,
    concat(ifnull(`v`.`supplier_id`, ''), ':Supplier Id:N:N:') AS `supplier_id`,
    concat(ifnull(`v`.`purchase_order_status`, ''), ':Purchase Order Status:O:N:') AS `purchase_order_status`,
    concat(ifnull(`v`.`grn_status`, ''), ':GRN Status:O:N:') AS `grn_status`,
    concat(ifnull(`v`.`purchase_order_creation_type`, ''), ':Purchase Order Creation Type:N:N:') AS `purchase_order_creation_type`,
    concat(ifnull(`v`.`purchase_order_life`, ''), ':Purchase Order Life:O:N:') AS `purchase_order_life`,
    concat(ifnull(`v`.`agent_paid_status`, ''), ':Agent Paid Status:N:N:') AS `agent_paid_status`,
    concat(ifnull(`v`.`supplier_state_id`, ''), ':Supplier State Id:N:N:') AS `supplier_state_id`,
    concat(ifnull(`v`.`supplier_city_id`, ''), ':Supplier City Id:N:N:') AS `supplier_city_id`,
    concat(ifnull(`v`.`approved_by_id`, ''), ':Approved By Id:O:N:') AS `approved_by_id`,
    concat(ifnull(`v`.`company_id`, ''), ':Company Id:N:N:') AS `company_id`,
    concat(ifnull(`v`.`company_branch_id`, ''), ':Company Branch Id:N:N:') AS `company_branch_id`,
    concat(ifnull(`v`.`financial_year`, ''), ':Financial Year :O:N:') AS `financial_year`
from
    `ptv_purchase_order_master_summary` `v`
limit 1;